Feature/alingment io 2
seqan/seqan3 pull request #1417
Opened 2019-12-10 20:26 UTC by eseiler

Blocked by #1415

2021-02-04 12:06 UTC, eseiler commented
I'm not going to work on this for now.
It needs adaptions in the format_bam_test, where the input and expected output are in binary format (uncompressed bam).
However, the BAM input is different from the SAM input (format_sam_test uses different input and format_bam_test claims it is the same input but in bam format).

The bam input is also not a valid bam, so I can't just revert it to a sam.
The format_bam_test probably needs a rework with known SAM files, otherwise I can't really add the hexadecimal array.

2021-02-05 12:52 UTC, SGSSGene requested changes

2021-02-05 12:52 UTC, SGSSGene commented on test/unit/io/alignment_file/format_sam_test.cpp
> +                                                                             "\tbH:H:1AE301\n"
Shouldn't here be a test which checks that the hex values was read?

2021-03-02 18:12 UTC, SGSSGene requested changes
Is it ok if I trust that you got all the hex values for the unit tests correct?

2021-03-02 18:12 UTC, SGSSGene commented on include/seqan3/io/alignment_file/format_bam.hpp
> +                if (*it == '\0')
I have troubling getting around the concept of `is_char<'\0'>(*it)`
So I am not sure if this should actually say `if (is_char<'\0'>(*it))`.

2021-03-02 18:12 UTC, SGSSGene commented on include/seqan3/io/alignment_file/format_bam.hpp
> +            target[tag] = byte_array;
This might profit from a `std::move`

```suggestion
            target[tag] = std::move(byte_array);
```

2021-03-02 18:17 UTC, eseiler commented on include/seqan3/io/alignment_file/format_bam.hpp
> +                if (*it == '\0')
```suggestion
                if (is_char<'\0'>(*it))
```

2021-03-02 18:18 UTC, eseiler commented on include/seqan3/io/alignment_file/format_bam.hpp
> +                if (*it == '\0')
Probably better to use the predicate

2021-03-02 18:19 UTC, eseiler commented
> Is it ok if I trust that you got all the hex values for the unit tests correct?

I  guess so, it would fail otherwise

2021-03-02 19:01 UTC, SGSSGene approved these changes
LGTM :+1:

2021-03-03 19:07 UTC, marehr reviewed
thank you :)

2021-03-03 19:07 UTC, marehr commented on include/seqan3/io/alignment_file/format_sam.hpp
> +        if constexpr (std::same_as<value_type, std::byte>)
here too add a note?

2021-03-03 19:23 UTC, eseiler commented on include/seqan3/io/alignment_file/format_sam.hpp
> +            read_sam_dict_vector(target[tag], stream_view, std::byte{});
The regex for `H` is `([0-9A-F][0-9A-F])*`, i.e. zero or more groups of two. samtools also throws if it's uneven

2021-03-03 19:24 UTC, eseiler commented on include/seqan3/io/alignment_file/format_sam.hpp
> +            read_sam_dict_vector(target[tag], stream_view, std::byte{});
I can do a new function.

2021-03-04 00:18 UTC, marehr approved these changes

2021-03-04 00:18 UTC, merged