[FEATURE] Alignment Configuration: Replace using_score_type tag for align_cfg::output with align_cfg::score_type
seqan/seqan3 pull request #2035
Opened 2020-08-14 14:17 UTC by Irallia

Will resolve https://github.com/seqan/product_backlog/issues/179

Still WIP

2020-08-14 15:46 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> +};
```suggestion
template <arithmetic score_t = int32_t>
struct score_type_tag : public pipeable_config_element<score_type_tag>
{
    //!\brief The selected score type.
    using score_type = score_t;

    //!\privatesection
    //!\brief Internal id to check for consistent configuration settings.
    static constexpr detail::align_config_id id{detail::align_config_id::score_type};
};
```

2020-08-14 15:46 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> +inline constexpr score_type_tag score_type{};
```suggestion
template <arithmetic score_t>
inline constexpr score_type_tag<score_t> score_type{};
```

2020-08-14 15:47 UTC, rrahn commented on test/snippet/alignment/configuration/align_cfg_score_type.cpp
> +    seqan3::configuration cfg = seqan3::align_cfg::score_type<>;
```suggestion
    seqan3::configuration cfg = seqan3::align_cfg::score_type<int16_t>; // Now the alignment computes 16 bit integers.
    seqan3::configuration cfg = seqan3::align_cfg::score_type<float>;  // Now the alignment computes float scores.
```

2020-08-31 11:43 UTC, simonsasse reviewed
Just tiny things 🧐💻

2020-08-31 11:43 UTC, simonsasse commented on include/seqan3/alignment/pairwise/alignment_configurator.hpp
> +        // If no output is set, everything will set by default.
Not sure, if you forgot a 'be' or if I'm not familiar with this way of saying it :)
```suggestion
        // If no output is set, everything will be set by default.
```

2020-08-31 11:43 UTC, simonsasse commented on include/seqan3/alignment/configuration/detail.hpp
> +        { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}  // 19: vectorised
```suggestion
        { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1}, // 15: result_type
        { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1}, // 16: score_type
        { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1}, // 17: scoring
        { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}  // 18: vectorised
```

2020-09-01 07:34 UTC, simonsasse approved these changes
Thanks, looks good to me :)

2020-09-02 08:04 UTC, rrahn requested changes
Thank you very much. Some changes I'd like to have :)

2020-09-02 08:04 UTC, rrahn commented on test/unit/alignment/configuration/align_config_score_type_test.cpp
> +    EXPECT_TRUE(cfg.exists<seqan3::align_cfg::score_type_tag<double>>());
```suggestion
    EXPECT_TRUE(cfg.exists<seqan3::align_cfg::score_type_tag<double>>());
    EXPECT_TRUE(cfg.exists<seqan3::align_cfg::score_type_tag>());
```

2020-09-02 08:04 UTC, rrahn commented on test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
> +    auto align_cfg_with_score_type = align_cfg;
But then this is not necessary. It does not makes sense to just copy it here. So you can work with the default align_cfg. Please update the part below to use the original align_cfg if we know already that it has an output configured.

2020-09-07 07:27 UTC, rrahn requested changes
Ok, second round is done. Looks quite good now! Thanks a lot.

2020-09-07 07:27 UTC, rrahn commented on doc/tutorial/pairwise_alignment/index.md
> +(corresponds to std::numeric_limits::max). Also the alignment and the front and back coordinates can be computed using a
```suggestion
(corresponds to std::numeric_limits::max). Also the alignment and the begin and end positions of the alignment can be computed using a
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> + * \brief Provides configuration for alignment output.
```suggestion
 * \brief Provides alignment configuration seqan3::align_cfg::score_type.
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> +#include <seqan3/core/algorithm/configuration.hpp>
```suggestion
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> +/*!\brief Helper variable used to configure the score type for the alignment algorithm.
```suggestion
/*!\brief A configuration element to set the score type used in the alignment algorithm.
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/configuration/align_config_score_type.hpp
> + * \relates seqan3::align_cfg::output_alignment
```suggestion
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/pairwise/alignment_configurator.hpp
> +        // Do not allow max error configuration for alignments not computing the edit distance.
```suggestion
        // Do not allow min score configuration for alignments not computing the edit distance.
```

2020-09-07 07:27 UTC, rrahn commented on include/seqan3/alignment/pairwise/alignment_result.hpp
> +     * configuration (see seqan3::align_cfg::detail::debug and seqan3::align_cfg::output_score).
```suggestion
     * configuration (see seqan3::align_cfg::detail::debug and seqan3::align_cfg::output_alignment).
```

2020-09-07 07:27 UTC, rrahn commented on test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
>                                        seqan3::align_cfg::detail::result_type<alignment_result_t>;
```suggestion
    auto align_cfg_with_result_type = align_cfg | seqan3::align_cfg::detail::result_type<alignment_result_t>;
```

2020-09-08 12:30 UTC, rrahn approved these changes
ok looks good now. Thank you very much. Can be rebased now and shipped :shipit:

2020-09-16 09:45 UTC, merged

2020-09-17 21:08 UTC, marehr commented
@Irallia Can you next time make sure that every single commit in your PRs can be compiled?

Commits in this PR
1. 9078045ca1047c9e8bf99e982171390e13032a67 does not compile
2. a8d81ce1a08feba4652175136bf84ef90e820787 does not compile
3. 9619f834b4c8286a01bd03faab546cc6d0601378 does not compile
4. a79d5d466c7b1e1a3e1d9d9bc9a11f84272a3369 does not compile
5. d0283da05e08904484ce6cc908d67d7a05fc1b05 does not compile
6. 8d0e389a0f7495706fc05b51de43650f30ec2229 does compile
7. f4e146c92f43e6d3c53452c3ba8e1c9ef40fe505 does compile

Otherwise, it makes it really hard to figure out which commit introduced a bug/regression.