[FIX] add anonymous namespace in type_traits
seqan/seqan3 pull request #2057
Opened 2020-08-18 13:32 UTC by marehr

2020-08-19 07:05 UTC, wvandertoorn commented
travis is unhappy about a type that uses the anonymous namespace [-Werror=subobject-linkage] in the `instatiate` struct in core/type_traits/lazy.hpp:49

2020-08-19 07:07 UTC, wvandertoorn requested changes
Travis is unhappy about a type that uses the anonymous namespace [-Werror=subobject-linkage] in the `instatiate` struct in core/type_traits/lazy.hpp:49

What is the gain for using an anonymous namespace here, what does it fix?

2020-08-19 08:00 UTC, eseiler commented
> What is the gain for using an anonymous namespace here, what does it fix?

Basically the same as `static`, but you can use it for everything. E.g. you can't to a `stattic` type.

2020-08-19 09:54 UTC, rrahn commented on include/seqan3/std/type_traits
> +}
```suggestion
} // namespace
```

maybe?

2020-08-20 23:27 UTC, marehr commented
I used the proper approach and fixed it via the feature testing macro; clang currently misses that macro, hence I created a bug ticket https://bugs.llvm.org/show_bug.cgi?id=47261

2020-08-27 06:43 UTC, smehringer approved these changes

2020-08-27 06:43 UTC, merged