[FIX] overload ranges::indirectly_readable_traits in cpp20 mode
seqan/seqan3 pull request #2077
Opened 2020-08-27 09:06 UTC by eseiler

When compiling with `-std=c++20`, we need to overload the `indirectly_readable_traits` in both `ranges` and `std` namespace.
The range-v3 lib still needs it's own concepts internally which then rely on `ranges::indirectly_readable_traits` being overloaded.

See https://cdash.seqan.de/viewBuildError.php?buildid=43442

2020-08-28 10:14 UTC, marehr requested changes
small changes; looks good to me

2020-08-28 10:14 UTC, marehr commented on test/include/seqan3/test/seqan2.hpp
>  #include <seqan3/std/ranges>
```suggestion
#include <range/v3/range_fwd.hpp>
#include <seqan/basic.h>
#include <seqan3/std/ranges>
```

Not sure about the ordering here (I think you are the master in ordering includes xD)

2020-08-28 10:14 UTC, marehr commented on test/include/seqan3/test/seqan2.hpp
>  //!\brief This makes seqan iterators ranges-aware, i.e. makes them fulfil ranges::readable which is in turn needed for
```suggestion
/*!\brief This makes seqan2 iterators ranges-aware, i.e. makes them fulfil ranges::indirectly_readable which is in turn
 *        needed for ranges::input_iterator and ranges::input_range.
 */
```

2020-08-28 10:14 UTC, marehr commented on test/include/seqan3/test/seqan2.hpp
> +//!ranges::input_range.
```suggestion
/*!\brief This makes seqan2 iterators ranges-aware, i.e. makes them fulfil std::indirectly_readable which is in turn
 *        needed for std::input_iterator and std::ranges::input_range.
 */
```

2020-08-30 20:49 UTC, marehr approved these changes

2020-09-02 10:58 UTC, smehringer approved these changes

2020-09-02 10:58 UTC, merged