[DOC] Add detailed documentation to the validator concept.
seqan/seqan3 pull request #2086
Opened 2020-09-01 07:07 UTC by smehringer

Resolves https://github.com/seqan/product_backlog/issues/152

2020-09-07 08:24 UTC, joergi-w requested changes

2020-09-07 08:24 UTC, joergi-w commented on include/seqan3/argument_parser/validators.hpp
> + * When adding (positional) options to the seqan3::argument_parser you may pass also pass a
```suggestion
 * When adding (positional) options to the seqan3::argument_parser you may pass a
```

2020-09-07 08:34 UTC, joergi-w approved these changes

2020-09-08 12:53 UTC, rrahn requested changes
Some suggestions. Otherwise looks good

2020-09-08 12:53 UTC, rrahn commented on include/seqan3/argument_parser/validators.hpp
> + * [functor](https://stackoverflow.com/questions/356950/what-are-c-functors-and-their-uses) that models
```suggestion
 * [function object](https://en.cppreference.com/w/cpp/named_req/FunctionObject) that models
```

2020-09-08 12:53 UTC, rrahn commented on include/seqan3/argument_parser/validators.hpp
> + * SeqAn provides several common-use-case validators, e.g. the seqan3::arithmetic_range_validator
```suggestion
 * SeqAn provides several common-use-case validators, e.g. the seqan3::arithmetic_range_validator.
```

2020-09-08 12:53 UTC, rrahn commented on include/seqan3/argument_parser/validators.hpp
> + * See the concept requirements for detailed information if you would like to implement your own validator.
```suggestion
 * To implement your own validator please refer to the detailed concept description below.
```
?

2020-09-09 13:37 UTC, rrahn approved these changes

2020-09-09 13:38 UTC, merged