[MISC] Rename view::some_iterator_name to view::[basic_]iterator
seqan/seqan3 pull request #2095
Opened 2020-09-03 14:31 UTC by wvandertoorn

Fixes https://github.com/seqan/product_backlog/issues/144.

Templated view iterators are renamed to 'basic_iterator', non-templated ones to 'iterator'

2020-09-07 06:56 UTC, simonsasse requested changes
Looks good, just a very tiny thing 👍

2020-09-07 06:56 UTC, simonsasse commented on include/seqan3/range/views/take.hpp
> +                                             std::is_nothrow_copy_constructible_v<basic_iterator>)
I think this should be aligned to the second noexcept. 🧐
```suggestion
    constexpr basic_iterator operator++(int) noexcept(noexcept(++std::declval<basic_iterator &>()) &&
                                                      std::is_nothrow_copy_constructible_v<basic_iterator>)
```

2020-09-07 06:56 UTC, simonsasse commented on include/seqan3/range/views/take.hpp
> +                                             std::is_nothrow_copy_constructible_v<basic_iterator>)
Same here:
```suggestion
    constexpr basic_iterator operator--(int) noexcept(noexcept(--std::declval<basic_iterator &>()) &&
                                                      std::is_nothrow_copy_constructible_v<basic_iterator>)
```

2020-09-10 08:59 UTC, simonsasse approved these changes
Thanks looks good ! 👌

2020-09-17 06:38 UTC, rrahn commented on include/seqan3/range/views/async_input_buffer.hpp
> +// → iterator.cached_value     [size 1]
```suggestion
// → iterator.cached_value [size 1]
```

2020-09-17 06:43 UTC, rrahn requested changes
OK, looks good in general. Only some minor indentation issue 💅 
Thank you

2020-09-17 06:43 UTC, rrahn commented on include/seqan3/range/views/async_input_buffer.hpp
>  // → async_input_buffer_view.buffer               [size n]
```suggestion
// → async_input_buffer_view.buffer [size n]
```

2020-09-17 11:42 UTC, rrahn approved these changes
Thanks

2020-09-17 11:42 UTC, merged