[MISC] Update the simd benchmark to use correct alignment output conf…
seqan/seqan3 pull request #2097
Opened 2020-09-05 10:50 UTC by rrahn

Follow up of changing to the output configuration of the alignment.

2020-09-05 13:19 UTC, rrahn commented
ci error not related:
```
99% tests passed, 1 tests failed out of 283

Total Test time (real) =  23.68 sec

The following tests FAILED:
	129 - argument_parser/detail/version_check_release_test (SEGFAULT)
Errors while running CTest
##[error]Process completed with exit code 8.
```

2020-09-08 10:50 UTC, rrahn commented on test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
> +                  seqan3::align_cfg::result{seqan3::with_score, seqan3::using_score_type<int16_t>},
```suggestion
                  seqan3::align_cfg::result{seqan3::with_end_positions, seqan3::using_score_type<int16_t>},
```

2020-09-08 10:51 UTC, marehr requested changes

2020-09-08 10:51 UTC, marehr commented on test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
> +                  seqan3::align_cfg::result{seqan3::with_score, seqan3::using_score_type<int16_t>},
```suggestion
                  seqan3::align_cfg::result{seqan3::with_end_positions, seqan3::using_score_type<int16_t>},
```

2020-09-08 10:51 UTC, marehr commented on test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
> +                  seqan3::align_cfg::result{seqan3::with_score, seqan3::using_score_type<int16_t>},
```suggestion
                  seqan3::align_cfg::result{seqan3::with_end_positions, seqan3::using_score_type<int16_t>},
```

2020-09-08 10:56 UTC, marehr approved these changes

2020-09-08 11:07 UTC, smehringer approved these changes
LGTM

2020-09-08 11:08 UTC, smehringer commented
I can't merge from my phone :D feel free to merge.

2020-09-08 11:56 UTC, merged