[Alignment configuration]
seqan/seqan3 pull request #2119
Opened 2020-09-16 16:00 UTC by smehringer

Final PR of #2032
Closes #2032

Resolves seqan/product_backlog/issues/96

2020-09-16 18:06 UTC, marehr commented
Can you rebase and make it compile?

2020-09-16 18:07 UTC, marehr requested changes
(Can you make it compile?)

2020-09-17 06:06 UTC, smehringer commented
Oh, when I made the PR it at least was mergeable.
Sure

2020-09-18 08:21 UTC, smehringer commented
@marehr everything should be fine now

2020-09-18 10:18 UTC, smehringer commented
Ok now even the snippets should be fine.

2020-09-18 13:37 UTC, marehr requested changes
Just small documentation stuff; thank you! :)

2020-09-18 13:37 UTC, marehr commented on doc/tutorial/pairwise_alignment/configurations.cpp
> +    // second sequence are not penelised:
```suggestion
    // Example of a semi-global alignment where leading and trailing gaps in the
    // second sequence are not penalised:
```

2020-09-18 13:37 UTC, marehr commented on doc/tutorial/pairwise_alignment/index.md
> +algorithm.
reflow this text

2020-09-18 13:37 UTC, marehr commented on doc/tutorial/pairwise_alignment/index.md
> +The edit distance can be further refined using the seqan3::align_cfg::min_score configuration to fix an edit score (a limit of the allowed number of edits).. If the
line limit and reflow following text

2020-09-22 09:46 UTC, marehr approved these changes
ty :)

2020-09-22 14:28 UTC, rrahn approved these changes

2020-09-22 14:29 UTC, rrahn commented
can you rebase real quick? Or can I squash merge?

2020-09-22 18:24 UTC, merged