[MISC] Update align_cfg::output_alignment to recent config design changes.
seqan/seqan3 pull request #2133
Opened 2020-09-18 18:34 UTC by rrahn

part of seqan/product_backlog#217

2020-09-21 08:22 UTC, MitraDarja approved these changes

2020-09-21 10:05 UTC, smehringer requested changes

2020-09-21 10:05 UTC, smehringer commented on include/seqan3/alignment/configuration/align_config_output.hpp
> +
Most other config elements without a member variable to dot not have explicit ctors

```suggestion
```

2020-09-22 05:56 UTC, smehringer approved these changes

2020-09-22 05:56 UTC, merged