[MISC] Update align_cfg::output_sequence2_id to recent config design changes.
seqan/seqan3 pull request #2135
Opened 2020-09-18 18:42 UTC by rrahn

part of seqan/product_backlog#217

2020-09-19 15:47 UTC, simonsasse approved these changes
👌

2020-09-21 10:03 UTC, smehringer requested changes

2020-09-21 10:03 UTC, smehringer commented on include/seqan3/alignment/configuration/align_config_output.hpp
> +
Most other config elements which do not have any member variable do not have explicit ctors
```suggestion
```

2020-09-22 05:54 UTC, smehringer approved these changes

2020-09-22 05:54 UTC, merged