[MISC] Update search_cfg::max_error_total to recent config design changes.
seqan/seqan3 pull request #2143
Opened 2020-09-19 09:16 UTC by rrahn

part of seqan/product_backlog#217

2020-09-19 12:00 UTC, marehr requested changes
PR does not build

2020-09-21 09:39 UTC, marehr approved these changes

2020-09-21 09:39 UTC, marehr commented on include/seqan3/search/detail/policy_max_error.hpp
> +        errors.total = to_error_count(total.error, query_size);
```suggestion
        errors.total = to_error_count(total.error, query_size);
```

@eseiler, @rrahn  This could now be part of the config now.

2020-09-21 14:55 UTC, rrahn commented on include/seqan3/search/configuration/max_error.hpp
> +    //!\brief  The number of total errors allowed for the search.
```suggestion
    //!\brief The error count or error rate.
```

2020-09-21 14:55 UTC, rrahn commented on include/seqan3/search/configuration/max_error.hpp
> +     * \param[in] error The error count used for the search.
```suggestion
     * \param[in] error The maximal number of deletion errors allowed in the search.
```

2020-09-21 14:56 UTC, rrahn commented on include/seqan3/search/configuration/max_error.hpp
> +     * \param[in] error The error rate used for the search.
```suggestion
     * \param[in] error The maximal error rate for deletions allowed in the search.
```

2020-09-22 05:51 UTC, smehringer approved these changes

2020-09-22 07:19 UTC, merged