[TEST] Add throw test for slice view to increase code coverage
seqan/seqan3 pull request #2175
Opened 2020-09-28 13:04 UTC by MitraDarja

Part of https://github.com/seqan/product_backlog/issues/222

2020-09-28 14:17 UTC, Irallia approved these changes
LGFM, thank you!

2020-09-30 14:50 UTC, smehringer requested changes

2020-09-30 14:50 UTC, smehringer commented on test/unit/range/views/view_slice_test.cpp
> +TEST(view_slice, throw)
`throw` isn't a very meaningful name. What are you testing here?

2020-10-01 08:18 UTC, smehringer approved these changes

2020-10-01 08:18 UTC, merged