[TEST] Add throw test for translate single view to increase code cove…
seqan/seqan3 pull request #2176
Opened 2020-09-28 13:09 UTC by MitraDarja

Part of https://github.com/seqan/product_backlog/issues/222

I would have added tests for the throws in lines 318 and 391, but if I understand the code correctly they can never be reached because the throw in line 212 will always throw first. Correct?
(Line number from translate.hpp, see: https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/range/views/translate.hpp)

2020-09-28 13:33 UTC, eseiler commented
> I would have added tests for the throws in lines 318 and 391, but if I understand the code correctly they can never be reached because the throw in line 212 will always throw first. Correct?
> (Line number from translate.hpp, see: https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/range/views/translate.hpp)

Can you check what happens with a default constructed view? Then the enum would be default initialised to `0` and the switch cases should use the default .

2020-09-30 13:45 UTC, MitraDarja commented
> > I would have added tests for the throws in lines 318 and 391, but if I understand the code correctly they can never be reached because the throw in line 212 will always throw first. Correct?
> > (Line number from translate.hpp, see: https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/range/views/translate.hpp)
> 
> Can you check what happens with a default constructed view? Then the enum would be default initialised to `0` and the switch cases should use the default .

For the following code:
```cpp
auto v7 = seqan3::detail::view_translate_single{vec};
    EXPECT_THROW(v7.size(), std::invalid_argument);
    seqan3::debug_stream << v7 << "\n";
    std::cout << v7.size();
```

I get the results:
 Actual: it throws nothing.
TYVR
4

Looks like it is initialized to the `seqan3::translation_frames::FWD_FRAME_0`

2020-09-30 14:26 UTC, eseiler commented
> > > I would have added tests for the throws in lines 318 and 391, but if I understand the code correctly they can never be reached because the throw in line 212 will always throw first. Correct?
> > > (Line number from translate.hpp, see: https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/range/views/translate.hpp)
> > 
> > 
> > Can you check what happens with a default constructed view? Then the enum would be default initialised to `0` and the switch cases should use the default .
> 
> @eseiler
> For the following code:
> 
> ```c++
> auto v7 = seqan3::detail::view_translate_single{vec};
>     EXPECT_THROW(v7.size(), std::invalid_argument);
>     seqan3::debug_stream << v7 << "\n";
>     std::cout << v7.size();
> ```
> 
> I get the results:
> Actual: it throws nothing.
> TYVR
> 4
> 
> Looks like it is initialized to the `seqan3::translation_frames::FWD_FRAME_0`

```cpp
auto v7 = seqan3::detail::view_translate_single{};
```
would be the default ctor.

2020-09-30 16:50 UTC, simonsasse approved these changes
Looks good :)

2020-10-01 17:16 UTC, eseiler commented
You can use `seqan3::views::translate_single(vec, seqan3::translation_frames{})` to test the throws for `size` and `operator[]`

2020-10-02 09:03 UTC, eseiler requested changes
Just 💅 

Can you rebase on the current master?
The coverage build doesn't see that `operator[]` is now covered....

2020-10-05 06:21 UTC, smehringer commented
@eseiler Looks good, feel free to do the second review and merge :)

2020-10-05 08:29 UTC, eseiler requested changes
I think we are missing the const versions?
Let's see what happens

2020-10-05 08:29 UTC, eseiler commented on test/unit/range/views/view_translate_test.cpp
>  }
```suggestion
    EXPECT_THROW(v7[0], std::invalid_argument);
    
    auto const v8 = seqan3::views::translate_single(vec, seqan3::translation_frames{});
    EXPECT_THROW(v8.size(), std::invalid_argument);
    EXPECT_THROW(v8[0], std::invalid_argument);
}
```

2020-10-05 21:04 UTC, eseiler commented
Ok, https://codecov.io/gh/seqan/seqan3/pull/2176/src/include/seqan3/range/views/translate.hpp now shows what's missing, even though the throw in 421 is definitely executed and tested...

2020-10-29 16:10 UTC, MitraDarja commented
@eseiler Rebasing on the new master did not solve this problem either... What should we do about it?

2020-10-29 16:54 UTC, eseiler commented
> @eseiler Rebasing on the new master did not solve this problem either... What should we do about it?

Can you look at https://codecov.io/gh/seqan/seqan3/pull/2176/src/include/seqan3/range/views/translate.hpp and check if the missing cases are run (either breakpoints in debugger or just some debug printing).

2020-11-02 09:58 UTC, eseiler approved these changes

2020-11-02 09:58 UTC, merged