[FIX] Underflow in search
seqan/seqan3 pull request #2178
Opened 2020-09-28 18:11 UTC by eseiler

AddressSanitizer on macOS sees this, others not....
Can be easily confirmed via using `.at()` instead of `[]`.

2020-09-29 12:05 UTC, marehr commented on include/seqan3/search/detail/search_scheme_algorithm.hpp
> +                        bool const go_right2 = block_id2 == 0 ? true : search.pi[block_id2] > search.pi[block_id2 - 1];
the exact same code twice, this screams for putting it into a single function..

2020-09-29 12:05 UTC, marehr approved these changes

2020-09-30 13:05 UTC, smehringer requested changes
This might be worth a changlog entry?

2020-09-30 14:24 UTC, eseiler commented
> This might be worth a changlog entry?

You're sure?
There is no meaningful way to describe the input that may lead the branches being evaluated in a way that causes the overflow + out of bounds access.
We can write `Fixed an issue where an invalid memory access may have happened in the search.` 
But it's not really helpful...

2020-09-30 14:47 UTC, smehringer commented
I see, alright then we won't make an entry :)

2020-09-30 14:48 UTC, smehringer approved these changes

2020-09-30 14:48 UTC, merged