[TEST] Add coverage to sequence file format fasta test
seqan/seqan3 pull request #2182
Opened 2020-10-02 08:06 UTC by MitraDarja

Part of https://github.com/seqan/product_backlog/issues/222

2020-10-02 09:29 UTC, eseiler requested changes

2020-10-02 09:29 UTC, eseiler commented on test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
> +    }};
```suggestion
    std::string input
    {
        ">ID1"
        "ACGTTTTTTTTTTTTTTT"
    };
    std::stringstream istream{input};
```

2020-10-02 09:29 UTC, eseiler commented on test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
> +    }};
```suggestion
    std::string input
    {
        ">ID1"
        "ACGTTTTTTTTTTTTTTT"
    };
    std::stringstream istream{input};
```

2020-10-05 08:33 UTC, eseiler approved these changes

2020-10-05 11:36 UTC, smehringer requested changes
Just one small thing because truncating ids would best be tested with something to truncate I guess

2020-10-05 11:36 UTC, smehringer commented on test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
> +        ">ID1"
```suggestion
        ">ID1 to_be_truncated"
```

2020-10-29 20:34 UTC, smehringer commented
well that's a bug then. Good thing we added a test. I sent you a patch on gitter that you can apply (I would do a separate [FIX] commit prior to the one adding the test)

2020-10-30 13:34 UTC, smehringer requested changes
Looks good! 
Can you just clean the commit history? It should look something like this:
`[FIX] Check if sequence is present when reading.`
`[TEST] Add fasta format test for no-newline--after-id-error.`

The Fix has to be *before* the Test such that the history is always "buildable" :)
``

2020-11-02 07:09 UTC, smehringer approved these changes
Perfect thanks :)

2020-11-02 07:09 UTC, merged