[INFRA] pass benchmark_min_time to performance tests
seqan/seqan3 pull request #2207
Opened 2020-10-13 15:18 UTC by eseiler

This should decrease the time needed for performance CI. (16m -> 2m)

I added an option to enable/disable this.

2020-10-14 09:50 UTC, marehr requested changes
I would simply pass this parameter instead of making it a boolean option.

2020-10-14 09:50 UTC, marehr commented on test/performance/CMakeLists.txt
> +option (SEQAN3_FAST_TESTS "Run each benchmark for a shorter time. Timings are unreliable." OFF)
```suggestion
option (SEQAN3_BENCHMARK_MIN_TIME "Set --benchmark_min_time= for each bechmark. Timings are unreliable in CI." 1)
```

2020-10-14 09:50 UTC, marehr commented on test/performance/CMakeLists.txt
> +    endif ()
```suggestion
    add_test (NAME "${test_name}" COMMAND ${target} "--benchmark_min_time=${SEQAN3_BENCHMARK_MIN_TIME}")
```

2020-10-14 09:50 UTC, marehr commented on .github/workflows/ci.yml
> +          cmake ../seqan3/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" -DSEQAN3_VERBOSE_TESTS=OFF -DSEQAN3_FAST_TESTS=ON
```suggestion
          cmake ../seqan3/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" -DSEQAN3_VERBOSE_TESTS=OFF -DSEQAN3_BENCHMARK_MIN_TIME=0.001
```

2020-10-14 10:14 UTC, marehr approved these changes

2020-10-14 10:14 UTC, marehr commented on .travis.yml
> +  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-fcompare-debug-second ${CXXFLAGS}" -DSEQAN3_VERBOSE_TESTS=OFF -DSEQAN3_FAST_TESTS=ON
```suggestion
  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-fcompare-debug-second ${CXXFLAGS}" -DSEQAN3_VERBOSE_TESTS=OFF -DSEQAN3_BENCHMARK_MIN_TIME=0.001```

2020-10-15 10:52 UTC, smehringer approved these changes

2020-10-15 10:53 UTC, merged