[INFRA] Remove algorithm/bound.hpp & alignment/band/static_band.hpp
seqan/seqan3 pull request #2272
Opened 2020-11-18 11:22 UTC by Irallia

Resolves partly seqan/product_backlog#160

Removed because not used.

Details for this: https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450

2020-11-18 20:44 UTC, marehr commented
@rrahn Why should this be deprecated? You can't do anything with that header anyway, shouldn't it just be removed?

2020-11-23 10:57 UTC, simonsasse approved these changes
Looks good to me :)

2020-11-23 20:02 UTC, smehringer commented
Since is something @rrahn requested I'll pass the review to him. I'll take on another PR

2020-11-25 10:20 UTC, rrahn requested changes
Thank you. There are some general differences to just deprecating the headers, since the actual classes need to be deprecated.

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/alignment/band/static_band.hpp
>  class static_band
Actually the class should be deprecated. 

```suggestion
class SEQAN3_DEPRECATED_310 static_band
```

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/alignment/band/static_band.hpp
>  class static_band
And then it would need an updated documentation that this class has been deprecated and one should use the align_cfg::band_fixed_size instead.

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/alignment/band/static_band.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0.")
This can be removed then, since the class itself gets deprecated

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/alignment/band/all.hpp
> + * \deprecated This header will be removed in 3.1.
```suggestion
 * \deprecated This header will be removed in 3.1.0; The contained functionality has been replaced by the seqan3::align_cfg::band_fixed_size configuration.
```

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/alignment/band/all.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0.")
Same text as above.

2020-11-25 10:20 UTC, rrahn commented on include/seqan3/core/algorithm/bound.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0.")
Here as well. We need the SEQAN3_DEPRECATED_310 macro before the strong type declarations and update the documentation of the classes with a deprecation notice.

2020-11-30 12:22 UTC, rrahn requested changes
Thank you. One little thing though.

2020-11-30 12:22 UTC, rrahn commented on include/seqan3/core/algorithm/all.hpp
> +#include <seqan3/core/algorithm/bound.hpp> // ToDo: remove this with the release SeqAn-3.1.0.
please add the macros to issue a warning message when the versions have been updated so we can't forget about this.

2020-12-05 13:16 UTC, rrahn approved these changes
thank you

2020-12-05 13:16 UTC, rrahn commented
Needs a rebase against current master. Thank you!

2020-12-07 13:46 UTC, merged