[MISC] Move core/common_tuple.hpp -> core/tuple/common_tuple.hpp
seqan/seqan3 pull request #2273
Opened 2020-11-18 15:06 UTC by eaasna

Partly resolves [seqan/product_backlog#160](https://github.com/seqan/product_backlog/issues/160)

2020-11-18 17:56 UTC, smehringer commented
Nice! :) All tests pass :+1: You can now request seqan/team on the right hand side, such that the first review round starts.

2020-11-23 07:16 UTC, smehringer commented
Rene and I are always doing the second review :) Other team members are doing the first. You can literally request `seqan/team` and it will randomly select one of the first review team members. Just search for `team` in the review box next time.

2020-11-23 09:29 UTC, MitraDarja requested changes
Looks good, well done! 👍 
Just two small things then it can go to the second review. Just request me again, once you have added the changes.

2020-11-23 09:29 UTC, MitraDarja commented on include/seqan3/core/common_tuple.hpp
> + *             Please \#include <seqan3/core/tuple/common_tuple.hpp> instead.
```suggestion
* \deprecated This header will be removed in 3.1.0; Please \#include <seqan3/core/tuple/common_tuple.hpp> instead.
```

2020-11-23 09:29 UTC, MitraDarja commented on include/seqan3/core/common_tuple.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1. "
```suggestion
SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0. "
```

2020-11-25 10:59 UTC, MitraDarja requested changes
Just two more things. There is a merge conflict now. Can you solve it? :)

2020-11-25 10:59 UTC, MitraDarja commented on include/seqan3/core/common_tuple.hpp
> +                         "Please #include <seqan3/core/tuple/common_tuple.hpp> instead.")
There is a new line missing in the end.

2020-11-25 13:29 UTC, eaasna commented on include/seqan3/core/common_tuple.hpp
> +                         "Please #include <seqan3/core/tuple/common_tuple.hpp> instead.")
Oh, thanks for noticing :)

2020-11-25 16:10 UTC, MitraDarja approved these changes
Looks good. 👍

2020-12-15 19:27 UTC, marehr commented
@smehringer Can you review this PR? It is waiting some days already :)

2020-12-15 20:13 UTC, smehringer commented
whoope I really thought I had reviewed that one. Thanks for the ping

2020-12-15 20:15 UTC, smehringer approved these changes
only a tiny thing

2020-12-15 20:15 UTC, smehringer commented on include/seqan3/core/common_tuple.hpp
> +                         "Please #include <seqan3/core/tuple/common_tuple.hpp> instead.")
```suggestion
SEQAN3_DEPRECATED_HEADER(
"This header is deprecated and will be removed in SeqAn-3.1.0 Please #include <seqan3/core/tuple/common_tuple.hpp> instead.")
```

2020-12-16 10:11 UTC, merged