Make dash usable for subcommand
seqan/seqan3 pull request #2306
Opened 2020-12-15 15:23 UTC by MitraDarja

Resolves https://github.com/seqan/product_backlog/issues/234

2020-12-15 15:42 UTC, eseiler requested changes
💅

2020-12-15 15:42 UTC, eseiler commented on CHANGELOG.md
> +* The subcommand of the `seqan3::argument_parser` can now contain a dash
```suggestion
* The subcommand of the `seqan3::argument_parser` may contain a dash
```

we try to avoid `now` because everything is `now` :)

2020-12-15 15:42 UTC, eseiler commented on test/unit/argument_parser/format_parse_test.cpp
> +    }
```suggestion
        EXPECT_NO_THROW((seqan3::argument_parser{"top_level",
                                                 2,
                                                 argv,
                                                 seqan3::update_notifications::off,
                                                 {"-dash"}}));
    }
```

2020-12-15 19:23 UTC, eseiler commented on CHANGELOG.md
> +* The subcommand of the `seqan3::argument_parser` can now contain a dash
I'd still prefer `may`, because we grant permission to use it. Though can and may are quite interchangeable in this case

2020-12-15 19:25 UTC, eseiler approved these changes
Sorry, didn't catch the missing braces in the first round. You can directly assign a second reviewer once done

2020-12-15 19:25 UTC, eseiler commented on include/seqan3/argument_parser/argument_parser.hpp
> +                                   "(regex: \"^[a-zA-Z0-9_-]+$\")."};
Since it now has multiple lines, we should add braces .. can you also do it for the other throw above?

2020-12-16 09:19 UTC, eseiler commented on include/seqan3/argument_parser/argument_parser.hpp
> +                                   "(regex: \"^[a-zA-Z0-9_-]+$\").")};
```suggestion
            if (!std::regex_match(sub, app_name_regex))
            {
                throw design_error{"The subcommand name must only contain alpha-numeric characters or '_' and '-' "
                                   "(regex: \"^[a-zA-Z0-9_-]+$\")."};
             }
```

we don't need the parentheses for the string, but the braces for `if` and `for`

2020-12-17 07:50 UTC, smehringer approved these changes
Looks good :+1:

2020-12-17 07:51 UTC, merged