[MISC] split seqan3/io/stream/iterator.hpp into multiple header
seqan/seqan3 pull request #2314
Opened 2020-12-22 10:53 UTC by marehr

2020-12-22 16:07 UTC, joergi-w requested changes
Thank you! I would like you to answer two questions and make one change:
1. Why don't we deprecate the empty file `iterator.hpp`? It is a pure include header now, similar to `all.hpp`. 
2. Do we need a changelog entry, as this is a public header? (If yes, please add.)

2021-01-13 00:24 UTC, marehr commented on include/seqan3/io/stream/detail/stream_buffer_exposer.hpp
> +// ============================================================================
```suggestion
```

2021-01-13 00:25 UTC, marehr commented on include/seqan3/io/stream/detail/stream_buffer_exposer.hpp
> +// ============================================================================
Done

2021-01-13 00:26 UTC, marehr commented
> Thank you! I would like you to answer two questions and make one change:
> 
>     1. Why don't we deprecate the empty file `iterator.hpp`? It is a pure include header now, similar to `all.hpp`.

True, I didn't want to do to much in this PR, but you are right I can remove that old header.

> 
>     2. Do we need a changelog entry, as this is a public header? (If yes, please add.)

This is not a problem, because ALL entities are detail and thus the header.

2021-01-13 10:04 UTC, joergi-w commented
Please check the header test...

2021-01-13 17:14 UTC, joergi-w approved these changes

2021-01-14 09:53 UTC, eseiler approved these changes

2021-01-14 09:53 UTC, merged