[FIX] Removing instances of [...]_index_specialisation
seqan/seqan3 pull request #2348
Opened 2021-01-20 16:22 UTC by eaasna

Remove concept fm_index_specialisationand concept bi_fm_index_specialisation and replace occurrences of such with seqan3::detail::template_specialisation_of<mytype, seqan3::fm_index> and seqan3::detail::template_specialisation_of<mytype, seqan3::bi_fm_index> or disjunction of both where they are used.

2021-01-20 16:25 UTC, eaasna commented on test/unit/search/fm_index/fm_index_collection_test_template.hpp
> +    EXPECT_TRUE((seqan3::detail::template_specialisation_of<index_t, seqan3::fm_index>));
Wasn't sure if this concept_check should just be deleted like in the case of #2339

2021-01-20 16:26 UTC, eaasna commented on test/unit/search/fm_index/fm_index_collection_test_template.hpp
> +        EXPECT_TRUE(seqan3::detail::template_specialisation_of<index_t, seqan3::bi_fm_index>);
Again, delete or no?

2021-01-25 09:16 UTC, marehr commented
```c++
../../../seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:530:48: error: ‘text_layout’ has not been declared
  530 |         requires (index_t::text_layout_mode == text_layout::single)
      |                                                ^~~~~~~~~~~
```

An include is missing?

2021-01-31 16:42 UTC, eseiler commented on include/seqan3/search/fm_index/concept.hpp
> -};
This must stay

2021-01-31 16:49 UTC, eaasna commented on include/seqan3/search/fm_index/concept.hpp
> -};
Thanks a lot!

2021-02-03 11:07 UTC, MitraDarja requested changes
Just some minor things.

2021-02-03 11:07 UTC, MitraDarja commented on include/seqan3/search/detail/unidirectional_search_algorithm.hpp
> +
Why did you add this new line?

2021-02-03 11:07 UTC, MitraDarja commented on include/seqan3/search/detail/unidirectional_search_algorithm.hpp
> + * \tparam index_t The type of index;
```suggestion
* \tparam index_t The type of index.
```

2021-02-03 11:07 UTC, MitraDarja commented on include/seqan3/search/detail/unidirectional_search_algorithm.hpp
> +     * \tparam index_t The type of index;
```suggestion
* \tparam index_t The type of index.
```

2021-02-03 11:07 UTC, MitraDarja commented on include/seqan3/search/fm_index/fm_index_cursor.hpp
> + * \tparam index_t The type of the underlying index;
```suggestion
 * \tparam index_t The type of the underlying index.
 ```

2021-02-03 13:30 UTC, eaasna commented on include/seqan3/search/detail/unidirectional_search_algorithm.hpp
> +
oops :)

2021-02-03 13:30 UTC, eaasna commented on include/seqan3/search/detail/unidirectional_search_algorithm.hpp
> + * \tparam index_t The type of index;
yes, thanks for noticing!

2021-02-03 16:10 UTC, MitraDarja approved these changes

2021-02-05 12:25 UTC, marehr commented on include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
> + * seqan3::detail::template_specialisation_of a seqan3::bi_fm_index_cursor.
```suggestion
 * \tparam index_t The type of the underlying index; index_t::cursor_type must model
 *                 seqan3::detail::template_specialisation_of a seqan3::bi_fm_index_cursor.
```

2021-02-05 12:25 UTC, marehr commented on include/seqan3/search/search.hpp
>            typename configuration_t = decltype(search_cfg::default_configuration)>
```suggestion
template <typename index_t,
          std::ranges::forward_range queries_t,
          typename configuration_t = decltype(search_cfg::default_configuration)>
```

2021-02-05 12:25 UTC, marehr commented on include/seqan3/search/detail/search_scheme_algorithm.hpp
> + * a seqan3::bi_fm_index_cursor.
```suggestion
 * \tparam index_t The type of index; index_t::cursor_type must model seqan3::detail::template_specialisation_of
 *                 a seqan3::bi_fm_index_cursor.
```

2021-02-05 12:25 UTC, marehr commented on include/seqan3/search/search.hpp
>            typename configuration_t = decltype(search_cfg::default_configuration)>
```suggestion
template <typename index_t,
          std::ranges::forward_range query_t,
          typename configuration_t = decltype(search_cfg::default_configuration)>
```

2021-02-05 12:25 UTC, marehr commented on include/seqan3/search/search.hpp
>            typename configuration_t = decltype(search_cfg::default_configuration)>
```suggestion
template <typename index_t,
          std::ranges::forward_range queries_t,
          typename configuration_t = decltype(search_cfg::default_configuration)>
```

2021-02-05 12:36 UTC, marehr commented on include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
> + *                 seqan3::detail::template_specialisation_of a seqan3::bi_fm_index_cursor.
```suggestion
 * \tparam index_t The type of the underlying index; This is normally seqan3::bi_fm_index.
```

2021-02-05 12:36 UTC, marehr commented on include/seqan3/search/fm_index/fm_index_cursor.hpp
> + * \tparam index_t The type of the underlying index.
```suggestion
 * \tparam index_t The type of the underlying index. This is normally seqan3::fm_index.
```

2021-02-05 12:36 UTC, marehr commented on test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp
> +                                                                                  seqan3::bi_fm_index_cursor>;
```suggestion
    static constexpr bool is_bi_fm_index = seqan3::detail::template_specialisation_of<typename index_type::cursor_type,
                                                                                      seqan3::bi_fm_index_cursor>;
```

2021-02-05 12:36 UTC, marehr commented on test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp
> +                                                                                  seqan3::bi_fm_index_cursor>;
```suggestion
    static constexpr bool is_bi_fm_index = seqan3::detail::template_specialisation_of<typename index_type::cursor_type,
                                                                                      seqan3::bi_fm_index_cursor>;
```

2021-02-05 12:43 UTC, marehr approved these changes
LGTM; I just fixed some indentation. Do you want to fix the history of the commits or can this be squashed merged?

2021-02-08 08:23 UTC, eaasna commented
@marehr Please squash merge

2021-02-08 09:25 UTC, merged