[TEST] use EXPECT_SAME_TYPE macro (oneline regexp)
seqan/seqan3 pull request #2369
Opened 2021-02-03 13:32 UTC by marehr

Search and replace with `EXPECT_TRUE\(\(std::same_as<(.+)>\)\);` and `EXPECT_SAME_TYPE($1);`

2021-02-03 13:32 UTC, marehr commented on test/unit/alignment/configuration/align_config_score_type_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
#include <seqan3/test/expect_same_type.hpp>
#include <seqan3/utility/type_traits/basic.hpp>
```

2021-02-03 13:33 UTC, marehr commented on test/unit/alignment/matrix/alignment_coordinate_test.cpp
> +
```suggestion
```

2021-02-03 13:33 UTC, marehr commented on test/unit/alignment/matrix/debug_matrix_test.cpp
```suggestion
```

2021-02-03 13:33 UTC, marehr commented on test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
```suggestion
```

2021-02-03 13:33 UTC, marehr commented on test/unit/alignment/pairwise/align_pairwise_test.cpp
```suggestion
```

2021-02-03 13:33 UTC, marehr commented on test/unit/alignment/pairwise/align_pairwise_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
#include <seqan3/test/expect_same_type.hpp>
#include <seqan3/utility/tuple/concept.hpp>
```

2021-02-03 13:34 UTC, marehr commented on test/unit/alignment/pairwise/alignment_configurator_test.cpp
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/alignment/pairwise/alignment_result_test.cpp
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/alignment/pairwise/detail/type_traits_test.cpp
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
> +
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> +
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/core/algorithm/pipeable_config_element_test_template.hpp
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/core/configuration/configuration_test.cpp
> +
```suggestion
```

2021-02-03 13:34 UTC, marehr commented on test/unit/core/detail/iterator_traits_test.cpp
```suggestion
```

2021-02-03 13:35 UTC, marehr commented on test/unit/io/alignment_file/sam_tag_dictionary_test.cpp
```suggestion
```

2021-02-03 13:35 UTC, marehr commented on test/unit/range/container/bitcompressed_vector_test.cpp
> +
```suggestion
```

2021-02-03 13:35 UTC, marehr commented on test/unit/range/container/small_vector_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/drop_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/repeat_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/single_pass_input_test.cpp
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/slice_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/take_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/range/views/type_reduce_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/search/configuration/hit_test.cpp
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/std/concept/core_language_test.cpp
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/test/seqan2_test.cpp
> +
```suggestion
```

2021-02-03 13:36 UTC, marehr commented on test/unit/utility/type_traits/function_traits_test.cpp
```suggestion
```

2021-02-03 13:37 UTC, eseiler commented
Did you forget to commit `seqan3/test/expect_same_type.hpp` ?

2021-02-03 13:38 UTC, marehr commented on test/unit/alignment/matrix/alignment_coordinate_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
#include <seqan3/test/expect_same_type.hpp>
#include <seqan3/test/pretty_printing.hpp>
```

2021-02-03 13:38 UTC, marehr commented on test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
#include <seqan3/test/expect_same_type.hpp>
```

2021-02-03 13:40 UTC, marehr commented on test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
```

2021-02-03 13:42 UTC, marehr commented on test/unit/std/concept/core_language_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
```

2021-02-03 13:42 UTC, marehr commented on test/unit/std/concept/core_language_test.cpp
> +    EXPECT_SAME_TYPE(int, int);
```suggestion
    EXPECT_TRUE((std::same_as<int, int>));
```

2021-02-03 14:14 UTC, marehr commented
> Did you forget to commit `seqan3/test/expect_same_type.hpp` ?
> 
> Edit: nvm, it's already in the lib

Yep, was implemented by #2312

2021-02-04 09:31 UTC, Irallia approved these changes
LGFM thank you!

2021-02-05 08:38 UTC, eseiler requested changes
LGTM, but can we move the `std` includes to the correct place while touching the files?

2021-02-05 08:38 UTC, eseiler commented on test/unit/io/alignment_file/sam_tag_dictionary_test.cpp
> +#include <seqan3/test/expect_same_type.hpp>
```suggestion
#include <seqan3/std/concepts>

#include <seqan3/io/alignment_file/sam_tag_dictionary.hpp>
#include <seqan3/test/expect_same_type.hpp>
```

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/container/small_vector_test.cpp
>  #include <seqan3/std/ranges>
Can you move this up, please?
Too far away to do a suggestion..

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/views/drop_test.cpp
>  #include <seqan3/std/ranges>
Also here + `std/algorithm` one line above

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/views/single_pass_input_test.cpp
>  #include <seqan3/std/ranges>
And here

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/views/slice_test.cpp
>  #include <seqan3/std/ranges>
= 1 line above

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/views/take_test.cpp
>  #include <seqan3/std/ranges>
+ line above

2021-02-05 08:38 UTC, eseiler commented on test/unit/range/views/type_reduce_test.cpp
>  #include <seqan3/std/ranges>
+ line above

2021-02-05 08:38 UTC, eseiler commented on test/unit/test/seqan2_test.cpp
>  #include <seqan3/test/seqan2.hpp>
```suggestion
#include <seqan3/std/ranges>

#include <seqan3/test/expect_same_type.hpp>
#include <seqan3/test/seqan2.hpp>
```

2021-02-05 09:56 UTC, eseiler approved these changes

2021-02-05 12:43 UTC, merged