[MISC] deprecate seqan3::alignment_coordinate
seqan/seqan3 pull request #2378
Opened 2021-02-14 19:34 UTC by SGSSGene

- Adds SEQAN3_DEPRECATE_310
- Adds \deprecated mesage
- Adds [DEPRECATED]
- No snippets or extra docu found.

2021-02-14 19:36 UTC, SGSSGene commented
Open: many other functions use `seqan3::alignment_coordinate` and probably have to be freed from it?

2021-02-17 14:40 UTC, MitraDarja approved these changes
LGTM. But can you check, what the problem with the CI is?

2021-03-22 15:20 UTC, Irallia commented on test/unit/alignment/pairwise/fixture/alignment_fixture.hpp
> +
Multiple new lines

2021-03-22 15:40 UTC, Irallia requested changes
Looks very good already. I would only rename begin1, begin2, end1, end2.
Also, I like your comment, but you are just using it very randomly.
```cpp
 // begin and end positions
        0u,
        0u,
        22u,
        12u,
        ```

2021-03-22 15:40 UTC, Irallia commented on test/unit/alignment/pairwise/fixture/alignment_fixture.hpp
> +    size_t end2_position;
Maybe give the variables clearer names:
```suggestion
    size_t begin_column_position;
    size_t begin_row_position;
    size_t end_column_position;
    size_t end_row_position;
```

2021-03-22 15:40 UTC, Irallia commented on test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
> +    EXPECT_EQ(end_positions.second, fixture.end2_position);
```suggestion
    EXPECT_EQ(end_positions.first, fixture.end_column_position);
    EXPECT_EQ(end_positions.second, fixture.end_row_position);
```
or
```suggestion
    EXPECT_EQ(end_positions.first, fixture.end_first_position);
    EXPECT_EQ(end_positions.second, fixture.end_second_position);
```
?

2021-03-22 15:40 UTC, Irallia commented on test/unit/alignment/pairwise/fixture/local_affine_banded.hpp
> +        // begin and end positions
You could add this comment in the other tests aswell 
eg `global_affine_unbanded.hpp`

2021-03-22 16:04 UTC, marehr commented on test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
> +    EXPECT_EQ(end_positions.second, fixture.end2_position);
They are called

* sequence1_begin_position
* sequence1_end_position
* sequence2_begin_position
* sequence2_end_position

https://docs.seqan.de/seqan/3-master-user/classseqan3_1_1alignment__result.html#a6f33588c817b822d0ebe7068d3072b6c

2021-03-22 16:07 UTC, marehr commented on test/unit/alignment/pairwise/fixture/global_affine_banded.hpp
> +        9u,
Maybe you can reapply your regex and add

```suggestion
        /*.sequence1_begin_position = */ 0u,
        /*.sequence2_begin_position = */ 0u,
        /*.sequence1_end_position = */ 16u,
        /*.sequence2_end_position = */ 9u,
```

2021-03-23 18:12 UTC, SGSSGene commented
Very good suggestions! I adjusted my regex so it actually works correctly...changed it to `.sequence1_begin_position` also added the suggested comments.

2021-03-25 11:53 UTC, Irallia approved these changes
Perfect, thank you!

2021-03-25 14:12 UTC, marehr approved these changes

2021-03-25 14:37 UTC, merged