[MISC] Argument Parser - improve help page
seqan/seqan3 pull request #2397
Opened 2021-02-22 16:13 UTC by Irallia

Resolves https://github.com/seqan/seqan3/issues/2396

2021-02-22 16:16 UTC, eseiler commented on include/seqan3/argument_parser/argument_parser.hpp
> +                    throw validation_error{"Value for option --version-check must be true or false."};
I would allow both `0` and `false`, otherwise this is an API break (do our bool options allow both `false` and `0`)?

2021-02-23 12:54 UTC, MitraDarja requested changes
LGTM, just a minor question. :)

2021-02-23 12:54 UTC, MitraDarja commented on include/seqan3/argument_parser/argument_parser.hpp
> + *  * disabling it for a specific application simply by setting the option `--version-check false` or
We know allow but 0 and false, maybe you should mention this here?

2021-02-23 12:54 UTC, MitraDarja commented on include/seqan3/argument_parser/argument_parser.hpp
> +     * - <b>\--version-check false/true</b> Disable/enable update notifications.
We know allow but 0 and false, maybe you should mention this here?

2021-02-23 14:04 UTC, MitraDarja approved these changes

2021-02-23 14:05 UTC, eseiler commented
@Irallia what about the last point in the issue? (`integer's`)

2021-02-23 16:09 UTC, Irallia commented
You can just sqash merge after you approve.

2021-02-23 17:15 UTC, eseiler approved these changes

2021-02-23 17:15 UTC, merged