[MISC] rename include/seqan3/io/{alignment => sam}_file
seqan/seqan3 pull request #2412
Opened 2021-02-24 15:46 UTC by marehr

Part of many small rename PRs, tackles https://github.com/seqan/product_backlog/issues/290.

2021-02-24 15:48 UTC, SGSSGene requested changes
Can you sort the includes?

2021-02-28 18:15 UTC, marehr commented
> Can you sort the includes?

Done, your script was handy :)

2021-03-02 17:27 UTC, SGSSGene requested changes
One ordering error left. Other wise LGTM :+1:

2021-03-02 17:27 UTC, SGSSGene commented on include/seqan3/io/all.hpp
> +#include <seqan3/io/sam_file/all.hpp>
Falsche reinfolge... (hat mein skript das übersehen?)

2021-03-02 17:29 UTC, SGSSGene commented on include/seqan3/io/all.hpp
>  #include <seqan3/io/record.hpp>
Falsche Reihenfolge:

```suggestion
#include <seqan3/io/exception.hpp>
#include <seqan3/io/record.hpp>
#include <seqan3/io/sam_file/all.hpp>
```

2021-03-02 17:32 UTC, SGSSGene approved these changes
:+1:

2021-03-02 19:37 UTC, eseiler approved these changes

2021-03-02 19:38 UTC, merged