[MISC] rename seqan3::{alignment => sam}_file_output*
seqan/seqan3 pull request #2414
Opened 2021-02-24 15:47 UTC by marehr

Part of many small rename PRs, tackles https://github.com/seqan/product_backlog/issues/290.

2021-03-01 13:33 UTC, Irallia requested changes
💅

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
>                               ref_info_not_given>;
```suggestion
sam_file_output(std::filesystem::path, selected_field_ids const &)
    -> sam_file_output<selected_field_ids, typename sam_file_output<>::valid_formats, ref_info_not_given>;
```

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
>                               ref_info_not_given>;
```suggestion
sam_file_output(stream_type &&, file_format const &, selected_field_ids const &)
    -> sam_file_output<selected_field_ids, type_list<file_format>, ref_info_not_given>;
```

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
>                               ref_info_not_given>;
```suggestion
sam_file_output(stream_type &, file_format const &, selected_field_ids const &)
    -> sam_file_output<selected_field_ids, type_list<file_format>, ref_info_not_given>;
```

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
>                               ref_info_not_given>;
same here

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
>                               ref_info_not_given>;
same here

2021-03-01 13:33 UTC, Irallia commented on include/seqan3/io/alignment_file/output.hpp
> +                      std::remove_reference_t<ref_ids_type>>;
```suggestion
sam_file_output(stream_type &&, ref_ids_type &&, ref_lengths_type &&, file_format const &)
    -> sam_file_output<typename sam_file_output<>::selected_field_ids,
                       type_list<file_format>,
                       std::remove_reference_t<ref_ids_type>>;
```

2021-03-01 14:18 UTC, marehr commented
@Irallia ty good catch :)

2021-03-01 18:32 UTC, Irallia approved these changes
perfect, thank you

2021-03-02 11:11 UTC, eseiler approved these changes

2021-03-02 11:11 UTC, eseiler commented on include/seqan3/io/alignment_file/input.hpp
> +     * There exists one more field for sam files, the seqan3::field::header_ptr, but this field is mostly used
```suggestion
     * There exists one more field for SAM files, the seqan3::field::header_ptr, but this field is mostly used
```

2021-03-02 11:58 UTC, merged