[TEST] use EXPECT_RANGE_EQ in aligned_sequence_builder_test...
seqan/seqan3 pull request #2449
Opened 2021-03-13 00:52 UTC by marehr

Part of seqan/product_backlog#83.

2021-03-13 16:26 UTC, MitraDarja requested changes
LGTM, but CI does not run through. :(

2021-03-15 13:56 UTC, marehr commented
> LGTM, but CI does not run through. :(

Can you approve then? Enrico will look out that the CI runs through :)

2021-03-15 13:59 UTC, MitraDarja approved these changes

2021-03-15 17:53 UTC, eseiler approved these changes

2021-03-15 17:53 UTC, merged