[FEATURE] Add simd store function.
seqan/seqan3 pull request #2504
Opened 2021-04-08 21:44 UTC by rrahn

Adds special store function to the simd utilities.
This function allows to store a simd vector to some memory region irrespective of the underlying memory alignment.
It wraps the intrinsics for SSE4, AVX2, an AVX512 and defaults to some sequential memory write in case a non builtin simd type is used.
The code is tested and documented. It does not affect any other code so far.

2021-04-08 21:55 UTC, rrahn commented on include/seqan3/utility/simd/detail/simd_algorithm_avx512.hpp
> +constexpr void store_avx512(void * mem_addr, simd_t const &);
```suggestion
constexpr void store_avx512(void * mem_addr, simd_t const & simd_vec);
```

2021-04-08 21:55 UTC, rrahn commented on include/seqan3/utility/simd/detail/simd_algorithm_sse4.hpp
> +constexpr void store_sse4(void * mem_addr, simd_t const &);
```suggestion
constexpr void store_sse4(void * mem_addr, simd_t const & simd_vec);
```

2021-04-09 10:20 UTC, Irallia requested changes
Looks good for me, but it looks like there are problems under linux. Request me again if it also runs under linux.

2021-04-09 11:38 UTC, Irallia approved these changes

2021-04-12 08:36 UTC, marehr approved these changes

2021-04-12 08:36 UTC, marehr commented on test/unit/utility/simd/simd_algorithm_test.cpp
> +
```suggestion
TYPED_TEST(simd_algorithm_memory, store)
{
    constexpr size_t length = seqan3::simd_traits<TypeParam>::length;

    std::vector<typename TestFixture::scalar_t> out_memory(length);
    seqan3::simd::store(out_memory.data(), seqan3::simd::iota<TypeParam>(0));

    for (size_t i = 0; i < length; ++i)
        EXPECT_EQ(static_cast<size_t>(out_memory[i]), i);
}

```

2021-04-12 14:10 UTC, merged