[MISC] Alphabet: rename phred68legacy to phred68solexa
seqan/seqan3 pull request #2522
Opened 2021-04-19 10:45 UTC by Irallia

Resolves: https://github.com/seqan/product_backlog/issues/315

2021-04-19 13:03 UTC, marehr commented
Snippets failed

```
 [ 65%] Building CXX object CMakeFiles/phred68solexa_snippet.dir/alphabet/quality/phred68solexa.cpp.o
In file included from /home/runner/work/seqan3/seqan3/seqan3/test/snippet/alphabet/quality/phred68solexa.cpp:1:0:
/home/runner/work/seqan3/seqan3/seqan3/include/seqan3/alphabet/quality/phred68legacy.hpp:26:13: error: This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/alphabet/quality/phred68solexa.hpp> instead. [-Werror]
    "This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/alphabet/quality/phred68solexa.hpp> instead.")
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/phred68solexa_snippet.dir/build.make:63: CMakeFiles/phred68solexa_snippet.dir/alphabet/quality/phred68solexa.cpp.o] Error 1
make[2]: Target 'CMakeFiles/phred68solexa_snippet.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:10534: CMakeFiles/phred68solexa_snippet.dir/all] Error 2
```

2021-04-19 14:56 UTC, MitraDarja approved these changes

2021-04-19 15:14 UTC, eseiler commented on CHANGELOG.md
> +  ([\#...](https://github.com/seqan/seqan3/pull/...)).
```suggestion
  ([\#2522](https://github.com/seqan/seqan3/pull/2522)).
```

2021-04-19 15:38 UTC, eseiler commented on CHANGELOG.md
> +  ([\#...](https://github.com/seqan/seqan3/pull/2522)).
```suggestion
  ([\#2522](https://github.com/seqan/seqan3/pull/2522)).
```

2021-04-19 15:40 UTC, eseiler commented on CHANGELOG.md
> +  ([\#...](https://github.com/seqan/seqan3/pull/2522)).
Can you move this down to the API changes section?

2021-04-19 15:40 UTC, eseiler commented on CHANGELOG.md
>    for usage.
Can you move this down to the API changes section (while we are at it)?

2021-04-19 16:42 UTC, eseiler requested changes
💅  + the stuff I wrote as comment before

2021-04-19 16:42 UTC, eseiler commented on CHANGELOG.md
> +  ([\#...](https://github.com/seqan/seqan3/pull/2522)).
I would rather write `renamed X to Y`
Deprecation is usually more for stuff that does not exist anymore

2021-04-20 14:29 UTC, eseiler commented on CHANGELOG.md
> +* Deprecated `seqan3::field::seq_qual`. Use `seqan3::fiel::seq` and `seqan3::field::qual` instead.
```suggestion
* Deprecated `seqan3::field::seq_qual`. Use `seqan3::field::seq` and `seqan3::field::qual` instead.
```

2021-04-20 14:31 UTC, eseiler commented on CHANGELOG.md
> +
```suggestion
* Renamed `seqan3::phred68legacy` to `seqan3::phred68solexa` ([\#2522](https://github.com/seqan/seqan3/pull/2522)).
* Renamed `seqan3::sam_dna16` to `seqan3::dna16sam`
  ([\#2521](https://github.com/seqan/seqan3/pull/2521)).

```

2021-04-20 14:32 UTC, eseiler approved these changes
Looks good, can you resolve the conflict?

2021-04-20 18:27 UTC, merged