[FIX] Move seqan3::views::char_to.hpp
seqan/seqan3 pull request #2530
Opened 2021-04-20 09:28 UTC by eaasna

Resolves [product_backlog/335](https://app.zenhub.com/workspaces/sprint-board-5f6aff703585d35fad17cc32/issues/seqan/product_backlog/335)

2021-04-20 16:16 UTC, SGSSGene approved these changes
:+1:

2021-04-21 07:50 UTC, eseiler requested changes

2021-04-21 07:50 UTC, eseiler commented on include/seqan3/range/views/char_to.hpp
> + * \deprecated This header will be removed in 3.1. Please use seqan3/utility/math.hpp instead.
```suggestion
 * \deprecated This header will be removed in 3.1. Please use seqan3/alphabet/views/char_to.hpp instead.
```

2021-04-21 09:47 UTC, eaasna commented
Thanks @eseiler I fixed the path. Could you squash merge or should I do it?

2021-04-21 10:02 UTC, eseiler approved these changes

2021-04-21 10:49 UTC, merged