Move complement
seqan/seqan3 pull request #2533
Opened 2021-04-20 11:29 UTC by eaasna

Resolves [product_backlog/336](https://app.zenhub.com/workspaces/sprint-board-5f6aff703585d35fad17cc32/issues/seqan/product_backlog/336)

- moved `complement.hpp` and the corresponding snippet to `seqan3/alphabet/views/`
- deprecated old header
- updated includes

2021-04-20 19:16 UTC, marehr commented on include/seqan3/alphabet/views/complement.hpp
> + * \hideinitializer
```suggestion
 * \hideinitializer
 *
 * \stableapi{Since version 3.1.}
```

2021-04-21 07:57 UTC, MitraDarja approved these changes
LGTM, but you touch a couple of files where seqan3/std-includes are not following our new standard (seqan3/std is supposed to go where std would go), it would be nice if you could fix that. :)

2021-04-21 08:01 UTC, eseiler requested changes
What Mitra said :)

And you'll need to rebase / resolve conflicts

2021-04-21 09:38 UTC, eaasna commented
Okay thanks I will place the std includes separately :) 

Should I also move `test/unit/range/views/complement_test.cpp` to `test/unit/alphabet/views/complement_test.cpp`? @eseiler

2021-04-21 10:01 UTC, eseiler commented
> Okay thanks I will place the std includes separately :)
> 
> Should I also move `test/unit/range/views/complement_test.cpp` to `test/unit/alphabet/views/complement_test.cpp`? @eseiler

Yes, please :)

2021-04-21 12:57 UTC, eaasna commented
I moved the test, created a new CMakeLists.txt and rebased. Please check again @eseiler

2021-04-21 13:32 UTC, eseiler requested changes

2021-04-21 13:32 UTC, eseiler commented on test/unit/range/views/get_test.cpp
> +#include <seqan3/std/ranges>
Can you move this up to the `iostream` include?

2021-04-21 13:32 UTC, eseiler commented on include/seqan3/range/views/all.hpp
>  #include <seqan3/range/views/deep.hpp>
```suggestion
#include <seqan3/alphabet/views/complement.hpp>
#include <seqan3/range/views/deep.hpp>
```

2021-04-21 14:23 UTC, eseiler approved these changes

2021-04-26 12:10 UTC, eseiler commented on include/seqan3/alphabet/views/complement.hpp
> +#include <seqan3/range/views/deep.hpp>
```suggestion
#include <seqan3/utility/views/deep.hpp>
```

2021-04-26 12:11 UTC, eseiler commented on test/unit/search/views/kmer_hash_test.cpp
>  #include <seqan3/alphabet/nucleotide/dna4.hpp>
```suggestion

#include <seqan3/alphabet/nucleotide/dna4.hpp>
```

2021-04-26 20:49 UTC, merged