[MISC] Move seqan3::views::single_pass_input to seqan3/utility/views/
seqan/seqan3 pull request #2535
Opened 2021-04-20 14:22 UTC by simonsasse

Resolves: https://github.com/seqan/product_backlog/issues/360

2021-04-20 16:20 UTC, SGSSGene approved these changes
:+1:

2021-04-20 16:21 UTC, SGSSGene requested changes
You need to move "test/snippet/range/views/single_pass_input.cpp" to test/snippet/utility...

2021-04-21 10:54 UTC, simonsasse commented
Thanks for the review. I rebased, moved the snippet as you demanded. I also moved the imports starting with seqan3/test back to the position. I separated them from the other seqan3 imports, because I thought it would correct. 👍

2021-04-21 11:49 UTC, simonsasse commented
I also need to move the seqan3/test/unit/range/views/single_pass_input_test.cpp to seqan3/test/unit/utility/views/single_pass_input_test.cpp.
I'll reassign then !

2021-04-21 16:09 UTC, SGSSGene approved these changes
:+1:

2021-04-21 16:40 UTC, marehr commented on include/seqan3/utility/views/single_pass_input.hpp
> +#include <seqan3/std/ranges>
```suggestion
#include <seqan3/std/concepts>
#include <seqan3/std/iterator>
#include <seqan3/std/ranges>

#include <seqan3/range/views/detail.hpp>
```

2021-04-21 16:41 UTC, marehr commented on test/snippet/range/views/take_until.cpp
> +#include <seqan3/utility/views/single_pass_input.hpp>     // for views::single_pass_input
```suggestion
#include <seqan3/utility/views/single_pass_input.hpp>  // for views::single_pass_input
```

2021-04-21 16:41 UTC, marehr commented on test/snippet/range/views/take_until.cpp
> +#include <seqan3/utility/views/single_pass_input.hpp>     // for views::single_pass_input
```suggestion
#include <seqan3/utility/char_operations/predicate.hpp> // for is_char
#include <seqan3/utility/views/single_pass_input.hpp>   // for views::single_pass_input
```

2021-04-21 16:42 UTC, marehr approved these changes

2021-04-21 16:42 UTC, marehr commented
rebase needed :)

2021-04-26 23:23 UTC, merged