move seqan3::views::slice to seqan3/utility/views/
seqan/seqan3 pull request #2542
Opened 2021-04-21 15:33 UTC by marehr

fixes https://github.com/seqan/product_backlog/issues/361

2021-04-23 09:07 UTC, MitraDarja approved these changes

2021-04-23 10:46 UTC, eseiler requested changes

2021-04-23 10:46 UTC, eseiler commented on test/unit/range/views/slice_test.cpp
>  #include <vector>
Shouldn't this be moved to utility?

2021-04-23 13:07 UTC, marehr commented on test/unit/range/views/slice_test.cpp
>  #include <vector>
👍🏽 good catch xD

2021-04-29 08:34 UTC, eseiler approved these changes

2021-04-29 08:34 UTC, merged