https://github.com/seqan/product_backlog/issues/298 follow-up
seqan/seqan3 pull request #2544
Opened 2021-04-21 16:16 UTC by marehr

resolves https://github.com/seqan/product_backlog/issues/298

2021-04-21 16:40 UTC, SGSSGene approved these changes
:+1:

2021-04-21 17:19 UTC, eseiler requested changes

2021-04-21 17:19 UTC, eseiler commented on include/seqan3/alphabet/aminoacid/concept.hpp
> +    /*!\brief CPO overload (check 1 out of 3 checks): explicit customisation via `seqan3::custom::alphabet`
```suggestion
    /*!\brief CPO overload (check 1 out of 3): explicit customisation via `seqan3::custom::alphabet`
```

etc.

2021-04-21 17:19 UTC, eseiler commented on include/seqan3/alphabet/concept.hpp
> +    /*!\brief CPO overload (check 2 out of 3 checks): argument dependent lookup (ADL), i.e. `assign_rank_to(rank, alphabet)`
```suggestion
    /*!\brief CPO overload (check 2 out of 3): argument dependent lookup (ADL), i.e. `assign_rank_to(rank, alphabet)`
```

Also has the advantage that the lines are not longer than 120

2021-04-22 09:36 UTC, eseiler approved these changes

2021-04-22 09:36 UTC, merged