[MISC] Alphabet: Move some views to alphabet views
seqan/seqan3 pull request #2545
Opened 2021-04-21 16:49 UTC by Irallia

Resolves https://github.com/seqan/product_backlog/issues/338 and
resolves https://github.com/seqan/product_backlog/issues/339 and
resolves https://github.com/seqan/product_backlog/issues/340 and
resolves https://github.com/seqan/product_backlog/issues/341 and
resolves https://github.com/seqan/product_backlog/issues/342.

- Move seqan::views::to_char to seqan3/alphabet/views/
- Move seqan::views::to_rank to seqan3/alphabet/views/
- Move seqan::views::trim_quality to seqan3/alphabet/views/
- Move seqan::views::translate_join to seqan3/alphabet/views/
- Move seqan::views::translate and seqan::views::translate_single to seqan3/alphabet/views/

2021-04-23 09:09 UTC, marehr commented on CHANGELOG.md
> +  ([\#2530](https://github.com/seqan/seqan3/pull/2530)) && ([\#...](https://github.com/seqan/seqan3/pull/...)).
```suggestion
```

2021-04-23 09:09 UTC, marehr commented on CHANGELOG.md
> +  ([\#2530](https://github.com/seqan/seqan3/pull/2530)) && ([\#...](https://github.com/seqan/seqan3/pull/...)).
(we list all moved header files before the release)

2021-04-26 11:29 UTC, Irallia commented on include/seqan3/alphabet/views/translate_join.hpp
> + * TODO: make this a snippet
Is the snippet in the later example not enough?
 -> \snippet test/snippet/alphabet/views/translate_join.cpp example

2021-04-26 11:33 UTC, Irallia commented on include/seqan3/alphabet/views/translate_join.hpp
> + * ```
Is the snippet in the later example not enough and this remains a note?
 -> \snippet test/snippet/alphabet/views/translate_join.cpp example

2021-04-27 14:31 UTC, MitraDarja approved these changes

2021-04-27 14:39 UTC, eseiler requested changes

2021-04-27 14:39 UTC, eseiler commented on include/seqan3/alphabet/views/all.hpp
> + * \brief Meta-header for the \link views views submodule \endlink.
```suggestion
 * \brief Meta-header for alphabet-related views.
```

2021-04-27 14:39 UTC, eseiler commented on test/performance/alphabet/CMakeLists.txt
> +seqan3_benchmark(view_translate_1D_benchmark.cpp)
Can you put these into `test/performance/alphabet/views/`

2021-04-28 16:29 UTC, eseiler approved these changes

2021-04-28 16:29 UTC, eseiler commented
Needs a rebase

2021-04-29 11:20 UTC, merged