[FIX] cmake-3.20: make add_include_dependencies work again
seqan/seqan3 pull request #2555
Opened 2021-04-23 10:13 UTC by marehr

This also adds a cmake warning if the header-dependency file is empty to make diagnostics easier if the whole mechanism doesn't work any more.

See introducing PR https://github.com/seqan/seqan3/pull/2261 for more details.

2021-04-26 11:49 UTC, SGSSGene approved these changes
*cmake wisdom*

2021-04-26 12:01 UTC, eseiler requested changes
Just 💅 

The important change is `CMAKE_DEPENDS_USE_COMPILER`?
And are the other changes important for that or just better style/error handling?

2021-04-28 11:34 UTC, marehr commented
> Just nail_care
> 
> The important change is `CMAKE_DEPENDS_USE_COMPILER`?

Yes

> And are the other changes important for that or just better style/error handling?

I also added some changes that makes the processing more robust, as the output format varied to that before (and did not work)

2021-04-28 16:30 UTC, eseiler approved these changes

2021-04-28 16:30 UTC, merged