[MISC] Lower case seqan3::translation_frames::*FRAME* and deprecate the uppercase versions.
seqan/seqan3 pull request #2565
Opened 2021-04-27 10:26 UTC by simonsasse

Resolves: https://github.com/seqan/product_backlog/issues/319

2021-04-27 10:37 UTC, eseiler commented on include/seqan3/range/views/translate.hpp
> +    FWD_FRAME_0 SEQAN3_DEPRECATED_310 = forward_frame0, //!< Please use the field name forward_frame0.
```suggestion
    FWD_FRAME_0 SEQAN3_DEPRECATED_310 = forward_frame0, //!< \deprecated Use seqan3::translation_frames::forward_frame0 instead.
```

etc.

2021-04-27 12:15 UTC, MitraDarja approved these changes

2021-04-27 14:35 UTC, eseiler requested changes

2021-04-27 14:35 UTC, eseiler commented on CHANGELOG.md
> +  ([\#2565](https://github.com/seqan/seqan3/pull/2565))
```suggestion
* Renamed `seqan3::translation_frames::*FRAME*` ([\#2565](https://github.com/seqan/seqan3/pull/2565)):
```

And then there needs to be a list (we did not just do upper to lower case, but also changed the names itself).
See the changelog entry for `([\#2459](https://github.com/seqan/seqan3/pull/2459))` for an example

2021-04-27 14:35 UTC, eseiler commented on include/seqan3/range/views/translate.hpp
> +    FWD_FRAME_0 SEQAN3_DEPRECATED_310 = forward_frame0, //!< \deprecated Use forward_frame0 instead.
```suggestion
    six_frames = forward_frames | reverse_frames, //!< All frames

    FWD_FRAME_0 SEQAN3_DEPRECATED_310 = forward_frame0, //!< \deprecated Use forward_frame0 instead.
```

2021-04-27 14:35 UTC, eseiler commented on test/snippet/range/views/translate_dna5.cpp
> +              seqan3::views::translate_single(seqan3::translation_frames::reverse_frame0);
```suggestion
    auto v9 = vec
            | seqan3::views::complement
            | seqan3::views::translate_single(seqan3::translation_frames::reverse_frame0);
```

2021-04-27 14:35 UTC, eseiler commented on test/unit/range/views/translate_join_test.cpp
> +              seqan3::views::translate_join(seqan3::translation_frames::forward_reverse0);
```suggestion
    auto v9 = vec
            | seqan3::views::complement
            | seqan3::views::translate_join(seqan3::translation_frames::forward_reverse0);
```

2021-04-27 16:29 UTC, simonsasse commented
Applied review and rebased. :)

2021-04-29 15:05 UTC, eseiler approved these changes

2021-04-29 15:12 UTC, simonsasse commented
sorry I messed up the rebase and had no time to fully fix it yet. Thanks for helping out ! :)

2021-04-29 15:18 UTC, merged