Move interleave and pairwise_combine
seqan/seqan3 pull request #2566
Opened 2021-04-27 10:29 UTC by MitraDarja

Resolves https://github.com/seqan/product_backlog/issues/352
Resolves https://github.com/seqan/product_backlog/issues/350

2021-04-27 16:09 UTC, SGSSGene requested changes
Looks good! Only have a few small things.

2021-04-27 16:09 UTC, SGSSGene commented on include/seqan3/range/views/interleave.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/utility/views/interleave.hpp> instead.")
```suggestion
SEQAN3_DEPRECATED_HEADER(
    "This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/utility/views/interleave.hpp> instead.")
```

2021-04-27 16:09 UTC, SGSSGene commented on include/seqan3/range/views/pairwise_combine.hpp
> +SEQAN3_DEPRECATED_HEADER("This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/utility/views/pairwise_combine.hpp> instead.")
```suggestion
SEQAN3_DEPRECATED_HEADER(
    "This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/utility/views/pairwise_combine.hpp> instead.")
```

2021-04-27 16:09 UTC, SGSSGene commented on test/unit/utility/views/CMakeLists.txt
>  seqan3_test (single_pass_input_test.cpp)
Can you remove all the other unnecessary white spaces?
so it is `seqan3_test(file.cpp)` (I checked there are 240 without whitespace and 60 entries with whitespaces)

2021-04-28 16:54 UTC, SGSSGene approved these changes
Thank you!

2021-04-28 22:03 UTC, marehr commented on include/seqan3/range/views/all.hpp
>  #include <seqan3/utility/views/deep.hpp>
this include order will be fixed if you rebase :)

2021-04-28 22:05 UTC, marehr commented on include/seqan3/utility/views/interleave.hpp
> + * \experimentalapi{Experimental since version 3.1.}
```suggestion
```

2021-04-28 22:05 UTC, marehr commented on include/seqan3/utility/views/pairwise_combine.hpp
> + * \experimentalapi{Experimental since version 3.1.}
```suggestion
```

2021-04-28 22:06 UTC, marehr approved these changes
you need to rebase :)

2021-04-29 08:33 UTC, MitraDarja commented
@marehr Can you (squash) merge?

2021-04-29 09:28 UTC, merged