range/views/Type reduce -> utility/views
seqan/seqan3 pull request #2587
Opened 2021-05-02 12:13 UTC by MitraDarja

Resolves https://github.com/seqan/product_backlog/issues/356

2021-05-03 09:09 UTC, Irallia approved these changes
LGFM, maybe some includes that are not needed.

2021-05-03 09:09 UTC, Irallia commented on test/unit/core/algorithm/detail/execution_handler_template.hpp
> +#include <seqan3/utility/views/type_reduce.hpp>
Is this include needed, or can it be removed?

2021-05-03 13:28 UTC, eseiler requested changes

2021-05-03 13:28 UTC, eseiler commented on include/seqan3/utility/views/type_reduce.hpp
> +}
Can you re-add + deprecate `type_reduce_view`

Also, can you add a changelog entry for the rename? 
> Renamed `seqan3::type_reduce_view` to `seqan3::type_reduce_t`

(we will do the changelog entry for the header moves at the very end, but we should document the rename as separate entry)

2021-05-07 12:00 UTC, eseiler commented on include/seqan3/utility/views/type_reduce.hpp
> +using type_reduce_view = decltype(views::type_reduce(std::declval<t>()));
```suggestion
template <typename t>
using type_reduce_view [[SEQAN3_DEPRECATED_310]] = type_reduce_t<t>;
```

2021-05-07 12:46 UTC, eseiler commented on CHANGELOG.md
> + * Renamed `seqan3::type_reduce_view` to `seqan3::type_reduce_t` ([\#2587](https://github.com/seqan/seqan3/pull/2587)).
```suggestion
  * Renamed `seqan3::type_reduce_view` to `seqan3::type_reduce_t` ([\#2587](https://github.com/seqan/seqan3/pull/2587)).
```

2021-05-07 12:46 UTC, eseiler commented on include/seqan3/utility/views/type_reduce.hpp
> +using type_reduce_view [[SEQAN3_DEPRECATED_310]] = type_reduce_t<t>;
```suggestion
using type_reduce_view SEQAN3_DEPRECATED_310 = type_reduce_t<t>;
```

2021-05-07 13:12 UTC, eseiler commented
Can you double-check that the old and new `type_reduce.hpp` are equivalent? There was an old header in the new (this PR) `type_reduce.hpp` that was in the meantime removed from the `type_reduce.hpp` on master.

2021-05-07 15:06 UTC, eseiler approved these changes

2021-05-07 15:37 UTC, merged