[DOC] Added more documentation for the mask submodule
seqan/seqan3 pull request #2590
Opened 2021-05-03 14:40 UTC by Irallia

Resolves #https://github.com/seqan/product_backlog/issues/313

Since there was already documentation, I just expanded it a bit and created links. I hope this corresponds to the desired result.

2021-05-04 14:42 UTC, MitraDarja approved these changes

2021-05-04 15:26 UTC, eseiler requested changes

2021-05-04 15:26 UTC, eseiler commented on include/seqan3/alphabet/mask/all.hpp
>   * transform another alphabet into a new alphabet that can represent the original alphabet plus masking information.
```suggestion
 * Masks are useful in cases where an alphabet needs to be augmented with additional information.
 * A common use case is the introduction of don't-care positions (*masking*) in \link nucleotide nucleotide \endlink or
 * \link aminoacid aminoacid \endlink sequences without using ``'N'`` or ``'X'``, respectively.
 * Instead, the original alphabet is combined with seqan3::mask to create a seqan3::masked composite.
 * When printed via the seqan3::debug_stream, masked characters are displayed in lowercase.
 *
 * \snippet TODO masked.cpp ?
 *
 * ### Types of masking
 *
 * There are two types of masking:
 *  * **hard-masking**, which converts masked characters to the ambiguous/unknown character (``'N'`` or ``'X'``)
 *  * **soft-masking**, which uses lowercase for masked characters
 *
 * ### Repeat masking
 *
 * The use of soft-masking was popularised by [RepeatMasker](https://www.repeatmasker.org/).
 * Interspersed repeats (transposons, retrotransposons and processed pseudogenes) and low complexity sequences are
 * denoted by lowercase characters. Note that larger repeats, such as segmental duplications, large tandem repeats and
 * whole gene duplications are generally not masked.
```

Can you fill in the `TODO` (link to the snippet)


I Removed access from repeatmasker and used https
(we don't really cite from there cite, so access date does not help that much)

THe part about repeat masking is very specific, so I gave it a header

2021-05-04 15:26 UTC, eseiler commented on include/seqan3/alphabet/mask/mask.hpp
> + * \see \link mask Mask submodule \endlink, it contains an explanation of hard-masking (UNKNOWN character) and
```suggestion
 * \see \link mask Mask submodule \endlink, it contains an explanation of hard-masking (unknown character) and
```

2021-05-04 15:26 UTC, eseiler commented on include/seqan3/alphabet/mask/mask.hpp
> + *
can you revert this?

2021-05-04 15:26 UTC, eseiler commented on include/seqan3/alphabet/mask/masked.hpp
> + *
Can you revert this?

2021-05-05 09:53 UTC, Irallia commented
you can merge squash if you are okay with the changes

2021-05-05 10:04 UTC, eseiler approved these changes
:+1:

2021-05-05 11:19 UTC, merged