rename bitcompressed_vector to bitpacked_sequence and move
seqan/seqan3 pull request #2592
Opened 2021-05-03 17:16 UTC by marehr

part of https://github.com/seqan/product_backlog/issues/377

2021-05-04 12:02 UTC, Irallia requested changes
LGFM, just a few style issues 💅

2021-05-04 12:02 UTC, Irallia commented on test/snippet/io/sequence_file/sequence_file_input_trait_overwrite.cpp
>      using sequence_alphabet = seqan3::dna4;               // instead of dna5
And here aswell (more or less spaces)

2021-05-04 12:14 UTC, eseiler commented on doc/tutorial/ranges/range_solution4.cpp
> +#include <seqan3/alphabet/container/bitpacked_sequence.hpp>     // include bitpacked sequence
```suggestion
```

2021-05-04 12:14 UTC, eseiler commented on doc/tutorial/ranges/range_solution4.cpp
>  #include <seqan3/alphabet/nucleotide/dna4.hpp>
```suggestion
#include <seqan3/alphabet/container/bitpacked_sequence.hpp>     // include bitpacked sequence
#include <seqan3/alphabet/nucleotide/dna4.hpp>
```

2021-05-04 12:14 UTC, eseiler commented on test/snippet/io/sam_file/sam_file_input_my_traits.cpp
>      using sequence_alphabet = seqan3::dna4;                        // instead of dna5
```suggestion
    using sequence_alphabet = seqan3::dna4; // instead of dna5
```

2021-05-04 12:14 UTC, eseiler commented on test/snippet/io/sequence_file/sequence_file_input_trait_overwrite.cpp
>      using sequence_alphabet = seqan3::dna4;               // instead of dna5
```suggestion
    using sequence_alphabet = seqan3::dna4; // instead of dna5
```

2021-05-04 13:14 UTC, Irallia approved these changes

2021-05-05 09:04 UTC, eseiler approved these changes

2021-05-05 09:04 UTC, eseiler commented on doc/tutorial/ranges/range_solution4.cpp
> +#include <seqan3/alphabet/container/bitpacked_sequence.hpp>     // include bitpacked sequence
```suggestion
```

2021-05-05 09:04 UTC, eseiler commented on doc/tutorial/ranges/range_solution4.cpp
>  #include <seqan3/alphabet/nucleotide/dna4.hpp>
```suggestion
#include <seqan3/alphabet/container/bitpacked_sequence.hpp>     // include bitpacked sequence
#include <seqan3/alphabet/nucleotide/dna4.hpp>
```

2021-05-05 22:07 UTC, merged