Deprecate/take exactly
seqan/seqan3 pull request #2601
Opened 2021-05-04 18:28 UTC by SGSSGene

Fixes https://github.com/seqan/product_backlog/issues/331

2021-05-05 08:27 UTC, MitraDarja approved these changes

2021-05-05 09:10 UTC, eseiler requested changes
The idea was that we do not just deprecate it but move it to `detail` because we need it internally, correct?
If so, can you do it like we have done it with the `persist` view? In short, we moved the view itself into detail and did the deprecation of the old header and the old view a bit differently

2021-05-05 09:10 UTC, eseiler commented on CHANGELOG.md
> +  [\#2601](https://github.com/seqan/seqan3/pull/2601).
```suggestion
  ([\#2601](https://github.com/seqan/seqan3/pull/2601)).
```

2021-05-10 08:43 UTC, SGSSGene commented
> The idea was that we do not just deprecate it but move it to `detail` because we need it internally, correct?
> If so, can you do it like we have done it with the `persist` view? In short, we moved the view itself into detail and did the deprecation of the old header and the old view a bit differently

Yes, you are right. I changed it accordingly.

2021-05-11 10:24 UTC, merged