Move debug stream
seqan/seqan3 pull request #2645
Opened 2021-05-12 18:58 UTC by marehr

Left-over of https://github.com/seqan/product_backlog/issues/160

2021-05-12 20:58 UTC, MitraDarja requested changes
LGTM, just some :nail_care:

2021-05-12 20:58 UTC, MitraDarja commented on include/seqan3/alignment/matrix/debug_matrix.hpp
> +#include <seqan3/core/debug_stream/optional.hpp>
Alphabetical order?

2021-05-12 20:58 UTC, MitraDarja commented on include/seqan3/alignment/matrix/detail/advanceable_alignment_coordinate.hpp
> +#include <seqan3/core/debug_stream/debug_stream_type.hpp>
Alphabetical order?

2021-05-12 20:58 UTC, MitraDarja commented on include/seqan3/core/detail/all.hpp
> +#include <seqan3/core/debug_stream/debug_stream_type.hpp>
Alphabetical order?

2021-05-12 21:01 UTC, marehr commented on include/seqan3/alignment/matrix/debug_matrix.hpp
> +#include <seqan3/core/debug_stream/debug_stream_type.hpp>
```suggestion
#include <seqan3/core/debug_stream/debug_stream_type.hpp>
#include <seqan3/core/debug_stream/range.hpp>
```

2021-05-12 21:01 UTC, marehr commented on include/seqan3/alignment/matrix/detail/advanceable_alignment_coordinate.hpp
> +#include <seqan3/core/debug_stream/debug_stream_type.hpp>
```suggestion
#include <seqan3/core/debug_stream/debug_stream_type.hpp>
#include <seqan3/core/debug_stream/tuple.hpp>
```

2021-05-12 21:02 UTC, marehr commented on include/seqan3/core/detail/all.hpp
> +#include <seqan3/core/debug_stream/debug_stream_type.hpp>
```suggestion
#include <seqan3/core/debug_stream/debug_stream_type.hpp>
#include <seqan3/core/debug_stream/optional.hpp>
#include <seqan3/core/debug_stream/range.hpp>
#include <seqan3/core/debug_stream/tuple.hpp>
```

2021-05-12 21:03 UTC, marehr commented on include/seqan3/alignment/matrix/debug_matrix.hpp
> +#include <seqan3/core/debug_stream/optional.hpp>
```suggestion
#include <seqan3/alphabet/detail/debug_stream_alphabet.hpp>
#include <seqan3/core/debug_stream/debug_stream_type.hpp>
#include <seqan3/core/debug_stream/optional.hpp>
#include <seqan3/core/debug_stream/range.hpp>
```

2021-05-12 22:07 UTC, MitraDarja approved these changes

2021-05-13 14:12 UTC, eseiler approved these changes

2021-05-13 14:13 UTC, merged