[MISC] remove SEQAN3_DEPRECATED_310 parts
seqan/seqan3 pull request #2684
Opened 2021-05-28 11:37 UTC by marehr

2021-05-29 09:00 UTC, MitraDarja requested changes
LGTM, but one minor thing. :)

2021-05-29 23:06 UTC, marehr commented on include/seqan3/io/sequence_file/input_options.hpp
>   */
done

2021-05-30 17:10 UTC, MitraDarja approved these changes

2021-06-04 07:30 UTC, eseiler approved these changes

2021-06-04 07:30 UTC, merged