[FIX] Constructing large fm_indices
seqan/seqan3 pull request #2756
Opened 2021-07-16 08:55 UTC by SGSSGene

Fixes unsigned vs signed int bug. This causes to limit the fm_index to
work for any text sizes above 2^31-1 base pairs.
This fix now allows up to 2^32-2 which is required for the human genome.

2021-07-19 08:29 UTC, Irallia approved these changes
LGFM, thanks for the explanation :)

2021-07-22 11:29 UTC, marehr approved these changes
Hmm, unfortunately we can't write `std::accumulate<size_t>` to make it more clear as the first argument is the iterator (see definition https://en.cppreference.com/w/cpp/algorithm/accumulate). This seems to be fixed by the standard with a default value version in `std::reduce`.

This is a terrible and hard to see error.

What I'm wondering is that you wrote 

> This fix now allows up to 2^32-2 which is required for the human genome.

But the initial value is `size_t`, so shouldn't the complete 64bit work for the size?

2021-07-22 11:31 UTC, marehr commented
Can we add a CHANGELOG entry?

2021-08-02 08:26 UTC, marehr requested changes
Changelog is missing; otherwise lgtm

2021-08-03 10:59 UTC, tloka commented
> What I'm wondering is that you wrote
> 
> > This fix now allows up to 2^32-2 which is required for the human genome.
> 
> But the initial value is `size_t`, so shouldn't the complete 64bit work for the size?

What is the answer to this? I would probably be close to the 2^32 limit soon, and it wouldn't allow to have forward + reverse sequences in one index for the human genome (which might be useful for some applications). Would be great to have the full 2^64 available.

2021-08-04 14:06 UTC, eseiler commented
> > What I'm wondering is that you wrote
> > > This fix now allows up to 2^32-2 which is required for the human genome.
> > 
> > 
> > But the initial value is `size_t`, so shouldn't the complete 64bit work for the size?
> 
> What is the answer to this? I would probably be close to the 2^32 limit soon, and it wouldn't allow to have forward + reverse sequences in one index for the human genome (which might be useful for some applications). Would be great to have the full 2^64 available.

I'd say it's a typo. It should say `2^64`.

2021-08-04 15:07 UTC, tloka commented
> I'd say it's a typo. It should say `2^64`.

I can confirm. I just successfully built an index of ~4.8GB with a local fix which wouldn't work for 2^32 (didn't use it for alignment yet though, but at least building finished without error).

2021-08-06 08:30 UTC, SGSSGene commented
> > I'd say it's a typo. It should say `2^64`.
> 
> I can confirm. I just successfully built an index of ~4.8GB with a local fix which wouldn't work for 2^32 (didn't use it for alignment yet though, but at least building finished without error).

Thanks for trying it out!. I have only seen the usage of `divsufsort` and read the wrong docu. The SDSL actually is distributed with its own version of divsufsort which handles larger integers.

2021-08-09 10:01 UTC, marehr approved these changes

2021-08-09 10:01 UTC, merged