[FIX] Restrict seqan3::alphabet_variant.
seqan/seqan3 pull request #2868
Opened 2021-10-27 08:36 UTC by smehringer

to only accept alphabets with the same underlying char type.

This cannot be tested, since incorrect code would not compile.

since all our alphabets have `char` as underlying type, this did not break anything.

Fixes #2867

2021-11-01 10:07 UTC, smehringer commented
Core Meeting 01.11.2021: 

We will restrict the `seqan3::alphabet_variant` to only work on chars. If we support wide chars can be tested once the use case arrives.

2021-11-02 10:12 UTC, Irallia requested changes
LGFM, just a spelling mistake.

2021-11-02 10:12 UTC, Irallia commented on include/seqan3/alphabet/composite/alphabet_variant.hpp
> +                  "Contact as on GitHub if you have a different use case https://github.com/seqan/seqan3 .");
```suggestion
                  "Contact us on GitHub if you have a different use case: https://github.com/seqan/seqan3 .");
```

2021-11-02 14:58 UTC, Irallia approved these changes

2021-11-04 10:55 UTC, eseiler approved these changes

2021-11-04 10:55 UTC, eseiler commented on include/seqan3/alphabet/composite/alphabet_variant.hpp
>                                                 (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
```suggestion
                                              (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
```

2021-11-04 10:55 UTC, eseiler commented on include/seqan3/alphabet/composite/alphabet_variant.hpp
> +                                               char>
```suggestion
                                              char>
```

2021-11-04 13:00 UTC, merged