[doc] update utility
seqan/seqan3 pull request #2871
Opened 2021-10-27 20:40 UTC by marehr

This is my first sweep for https://github.com/seqan/product_backlog/issues/393

I didn't put any `\remark` yet, because most entities are stand-alone and don't really have anything "globally" explained at the submodule page.

Maybe the tuple documentation could have this, but I'm not sure. A draft for this is here: https://github.com/marehr/seqan3/pull/new/doc_utility2

2021-11-01 07:43 UTC, SGSSGene requested changes
I think we should state which c++ version doesn't have the concept yet, so that future developers have a time point when this statement was valid.

2021-11-01 07:43 UTC, SGSSGene commented on include/seqan3/utility/views/all.hpp
> + * The C++ standard doesn't have this concept yet.
To make this more "timeless" maybe:
```suggestion
 * The C++20 standard doesn't have this concept.
```

2021-11-01 07:43 UTC, SGSSGene commented on include/seqan3/utility/views/all.hpp
> + * The C++ standard doesn't have this concept yet.
Same here.

2021-11-04 13:15 UTC, SGSSGene approved these changes
Nice improvements to the documentation :-)

2021-11-04 14:56 UTC, smehringer approved these changes

2021-11-04 14:56 UTC, merged