[INFRA] List unused snippets in source dir correctly.
seqan/seqan3 pull request #2900
Opened 2021-11-23 09:22 UTC by smehringer

This does not affect seqan3 right now because we don't have snippets in `/test/snippet` directly. Reusing the `list_unused_snippets.cmake` in other repos (e.g. argument parser), will fail if snippets are on the `current cmake source dir`.

This PR fixes it in seqan3 so we never run into the problem in case we do have a snippet in `/test/snippet` at some point.

2021-11-23 09:26 UTC, SGSSGene approved these changes
I am unsure of what the best way is to do this. So I will accept this PR :+1:

2021-11-23 09:55 UTC, smehringer commented
> I am unsure of what the best way is to do this. So I will accept this PR +1

yeah me neither. This does what I want. I don't know if there is a prettier solution.

2021-11-23 13:05 UTC, eseiler requested changes
I propose:

```patch
diff --git a/test/cmake/diagnostics/list_unused_snippets.cmake b/test/cmake/diagnostics/list_unused_snippets.cmake
index ba9de9b5d..5e573cdba 100644
--- a/test/cmake/diagnostics/list_unused_snippets.cmake
+++ b/test/cmake/diagnostics/list_unused_snippets.cmake
@@ -31,13 +31,13 @@ function (list_unused_snippets snippet_base_path)
         # e.g. /seqan3/test/snippet/../../doc/tutorial/pairwise_alignment
         get_filename_component (source_dir "${source}" DIRECTORY)
         # e.g. ../../doc/tutorial/pairwise_alignment
-        file (RELATIVE_PATH source_relative_dir "${snippet_base_path}" "${source_dir}")
+        file (RELATIVE_PATH source_relative_stem "${snippet_base_path}" "${source_dir}/${source_wle}")
 
         # test_snippet_output_list adds all potential cout / cerr files even if they don't really exist
         # This list will be subtracted from the real list of files, so it can contain "more" without changing the
         # result.
-        list (APPEND test_snippet_output_list "${source_relative_dir}/${source_wle}.out")
-        list (APPEND test_snippet_output_list "${source_relative_dir}/${source_wle}.err")
+        list (APPEND test_snippet_output_list "${source_relative_stem}.out")
+        list (APPEND test_snippet_output_list "${source_relative_stem}.err")
     endforeach ()
 
     # create the difference between test_snippet_output_glob_list set and test_snippet_output_list set.
```

2021-11-24 16:07 UTC, smehringer commented
> I propose:
> `... patch`

Thanks this looks better! I also validated that it works.

2021-11-24 16:13 UTC, eseiler approved these changes

2021-11-24 16:28 UTC, merged