[DOC, BUG] Clarify flag default value
seqan/seqan3 pull request #2946
Opened 2022-02-21 13:53 UTC by eaasna

seqan3 side of https://github.com/seqan/sharg-parser/issues/65

2022-02-22 14:58 UTC, SGSSGene approved these changes

2022-03-04 11:45 UTC, eseiler requested changes

2022-03-04 11:45 UTC, eseiler commented on doc/tutorial/argument_parser/index.md
> +as `_`, `-`, or `@`, but never start with `-`.
```suggestion
  as `_`, `-`, or `@`, but never start with `-`.
```

2022-03-04 11:45 UTC, eseiler commented on doc/tutorial/argument_parser/index.md
> +* Either the short or long id may be empty but not both at the same time.
```suggestion
* Either the short or long id may be empty, but not both at the same time.
```

2022-03-04 11:45 UTC, eseiler commented on doc/tutorial/argument_parser/index.md
> +* **Flags**: value must be false by default. Passing the flag identifier on the command line marks it as true.
```suggestion
* **Flags**: The default value must be false. Passing the flag identifier on the command line sets it to true.
```

2022-03-04 11:45 UTC, eseiler commented on doc/tutorial/argument_parser/index.md
> +are predefined and cannot be specified manually or used otherwise.
```suggestion
  are predefined and cannot be specified manually or used otherwise.
```

2022-03-04 11:45 UTC, eseiler commented on doc/tutorial/argument_parser/index.md
> +
```suggestion
\note Unlike regular options which take id-value pairs, flags are passed as an identifier only. The flag's default value
must be false and is set to true when the flag is present on the command line.

``

2022-03-04 11:45 UTC, eseiler commented on include/seqan3/argument_parser/argument_parser.hpp
> +     * \param[in, out] value     The variable which shows if the flag is turned off (default) or on.
```suggestion
     * \param[in, out] value     The variable which shows whether the flag is turned off (default) or on.
```

2022-03-04 11:45 UTC, eseiler commented on include/seqan3/argument_parser/argument_parser.hpp
> +     * \throws seqan3::design_error
```suggestion
     * \throws seqan3::design_error if `value` is true.
```

2022-03-09 15:44 UTC, merged