[DOC] clarification how shapes are applied in kmer-hash
seqan/seqan3 pull request #2981
Opened 2022-05-16 09:19 UTC by SGSSGene

This adds some clarification on the direction of how shapes are applied when computing hashes.
This intends to solve #2832

2022-05-16 09:41 UTC, eseiler approved these changes
👍 
But let's see what we resolve in the dev meeting

2022-05-16 09:41 UTC, eseiler commented on include/seqan3/search/views/kmer_hash.hpp
> + * the sequence AGT.
```suggestion
 * \attention The Shape is defined from right to left. The mask 0b1101 applied to ACGT will return
 * the sequence AGT.
```

2022-05-16 09:41 UTC, eseiler commented on test/snippet/search/views/kmer_hash.cpp
> +    // the same result as mask 0b111 applied to AGT.
```suggestion
    // Note: the Shape is defined from right to left. The mask 0b1101 applied to ACGT will yield
    // the same result as mask 0b111 applied to AGT.
```

2022-05-16 18:53 UTC, smehringer commented on include/seqan3/search/views/kmer_hash.hpp
> + * the sequence AGT.
why is this an `attention`? Isn't this intuitive to read the shape from left to right?

Also:
```suggestion
 * \note The Shape is defined from right to left. The mask 0b1101 applied to "ACGT" is 
 * interpreted as "A.GT" will return the hash value for "AGT".
```

2022-05-16 18:56 UTC, smehringer requested changes
small :nail_care:

2022-05-16 19:11 UTC, smehringer requested changes

2022-05-16 19:11 UTC, smehringer commented on test/snippet/search/views/kmer_hash.cpp
> +    }
```suggestion
    // Attention: the Shape is defined from right to left! 
    // The mask 0b11111101 applied to "AGAAAATA" ("A.AAAATA") will yield
    // the same hash value as mask 0b1111111 applied to "AAAAATA".
    {
        auto text1 = "AGAAAATA"_dna4;
        auto text2 = "AAAAATA"_dna4;
        seqan3::debug_stream << (text1 | seqan3::views::kmer_hash(0b11111101_shape)) << '\n'; // [TODO?]
        seqan3::debug_stream << (text2 | seqan3::views::kmer_hash(0b1111111_shape)) << '\n';  // [TODO?]
    }
```

2022-05-17 10:54 UTC, smehringer approved these changes

2022-05-17 10:55 UTC, merged