[DOC] More doxygen 1.9.6 fixes
seqan/seqan3 pull request #3080
Opened 2022-10-25 10:03 UTC by eseiler

See nightlies: https://cdash.seqan.de/test/5002562

2022-10-26 09:39 UTC, SGSSGene approved these changes

2022-10-26 11:26 UTC, smehringer requested changes
is it worth to introduce all these workarounds?
Can't we instead file doxygen bugs and hope that the'll be fixed before updating?

2022-10-26 11:36 UTC, eseiler commented
> is it worth to introduce all these workarounds? Can't we instead file doxygen bugs and hope that the'll be fixed before updating?

The links aren't a bug, good luck getting a minimal example for the `value_type` thingie, they don't react on the workaround issue...
So, kinda easier to just workaround/fix

2022-10-31 14:17 UTC, smehringer approved these changes

2022-10-31 14:17 UTC, merged