[MISC] Add field::alignment deprecation to sam_file_output.
seqan/seqan3 pull request #3087
Opened 2022-11-01 12:14 UTC by smehringer

I forgot to add the static assert to the output file :see_no_evil:

2022-11-02 08:29 UTC, SGSSGene requested changes

2022-11-02 08:29 UTC, SGSSGene commented on include/seqan3/io/sam_file/output.hpp
> +                  "The field::alignment is deprecated and only field::cigar is supported. Please see "
ich glaube der Begriff `deprecated` ist nicht richtig. Es ist ja nicht `deprecated` sondern `removed`.

2022-11-02 11:13 UTC, smehringer commented
I can change both in this PR. Maybe `was removed` is more accurate?

2022-11-02 11:16 UTC, eseiler commented
> I can change both in this PR. Maybe `was removed` is more accurate?

`The field::alignment was removed. Please see...`?

It's more accurate :D

2022-11-07 09:21 UTC, eseiler approved these changes

2022-11-07 09:38 UTC, merged